README.md
The only reference to this env var was in the changelog and code, but not in the documentation. It could be useful to someone here.
Also formatted the long docker commands to make them easier to read on narrow windows
=> Add note regarding DB_ALL_NAMES variable to README

input/postgres/relation_stats.go
Previously the collector was effectively hanging when it encountered an index that has an ExclusiveLock held (e.g. due to a non-concurrently running REINDEX).
=> Index statistics: Don't run relation_size on exclusively locked indices

runner/queries.go
Previously this was first reading the server values, and then waiting on
the mutex. In the case a full snapshot took longer than 1 minute, that
meant that this was waiting for a full snapshot in the mutex.
Unfortunately, the full snapshot writes the server.PrevState value at the
very end of its run - which was discarded based on the fact that the
compact snapshot worker had already cached an older previous state in the
"server" variable.
Small as it may seem, this was the cause of a slow but steady memory leak,
because the UnidentifiedStatementStats field of the PersistedState struct
just kept growing.
This also may have caused incorrect values to show for other statistics,
due to diffs not using the correct previous values.
In passing, parallelize the collection of the high-frequency …
=> High-frequency query collection: Avoid race condition, run in parallel

.github/workflows/ci.yml
@lfittl thoughts? This is really just a smoke test, but it's a start. Anything else on the shortlist for adding to CI?
=> Add basic CI via GitHub Actions

config/read.go
This enables the following settings to work correctly when used in
Docker/Heroku:
- DB_NAME
- DB_SSLROOTCERT_CONTENTS
- DB_SSLCERT_CONTENTS
- DB_SSLKEY_CONTENTS
=> Refactor pre-processing of config values

input/system/google_cloudsql/log_receiver.go, input/system/google_cloudsql/test_run.go
For now I copied the method to get the prefix from the self-hosted check--I can move that to a helpers file. Where do you think it should go?
=> Add log_line_prefix check to GCP self-test

input/system/google_cloudsql/log_subscriber.go
This may cause problems with messages not being correctly cleaned up
otherwise, and we already have a configuration where the collector
is the only intended receiver of messages.
=> Cloud SQL: Always acknowledge Pub Sub messages

README.md
I was on a call with pganalyze engineers and they recommended this var. I tested it and it worked once I set this along with [http_put_response_hop_limit](https://github.com/pganalyze/collector/issues/128) 2 :rocket:
=> add necessary env var

input/postgres/schema.go
Right now, the flag indicates whether schema collection was successful
for a particular database, but we set it if we are at all able to
connect to a database, even if the actual data collection fails
afterward (we print warnings but that's not sufficient here).
Instead, only set the flag if collection of relation and function
metadata, and of relation and index stats, all succeed.
=> Ensure we only set collected_local_catalog_data when appropriate

main.go
Add the privilege drop test when running as root.
@lfittl is this the right approach here? The test path is a little hard to follow.
=> Improve --test-logs behavior

packages/repo/Makefile
Make is unnecessarily picky about this :-)
=> packages/repo Makefile: Fix tabs vs spaces typo

go.mod, go.sum, vendor/github.com/pganalyze/pg_query_go/v2/CHANGELOG.md, vendor/github.com/pganalyze/pg_query_go/v2/Makefile, vendor/github.com/pganalyze/pg_query_go/v2/parser/parser.go, vendor/github.com/pganalyze/pg_query_go/v2/parser/pg_query_normalize.c, vendor/modules.txt
=> Update to pg_query_go 2.0.2

setup/main.go, setup/state/state.go
* if not run as root
* if reading configuration file fails
* if user decides not to continue after reading intro
=> Expand telemetry for guided setup failures

.github/workflows/ci.yml, Makefile, config/config.go, config/read.go, input/postgres/statements.go, input/postgres/types.go, input/system/google_cloudsql/log_subscriber.go, input/system/rds/logs.go, input/system/selfhosted/system.go, main.go, output/pganalyze_collector/null_double.go, output/transform/postgres_relations.go, output/transform/postgres_types.go, state/postgres_relation_stats.go, tools.go, util/clean_http_error.go, util/reload_fallback.go, util/reload_posix.go
- Run go fmt ./...
- Add linting to CI
=> Add basic 'go fmt' linting to CI

input/postgres/types.go
Currently, we always expect domains to have at least one constraint
defined, and collecting custom type information breaks when that's not
the case.
Handle the case of domains with no constraints.
=> Fix handling of custom domains with no constraints

CHANGELOG.md, packages/Makefile, util/version.go
=> Release 0.41.3

main.go
This avoids lost statistics when the collector is reloaded mid-cycle
between the full snapshot runs. Since the reload logic reads in the state
file its important that any state we want to persist across reloads is
written out beforehand (such as the high-frequency query statistics).
=> Write state file before reloading collector

contrib/install.sh, packages/repo/Dockerfile.repo-deb, packages/repo/Dockerfile.repo-rpm, packages/repo/Makefile, packages/repo/sync_rpm.sh
These changes were necessary to resolve some oversights by myself in https://github.com/pganalyze/collector/pull/230
=> Fix package install

CHANGELOG.md, packages/Makefile, util/version.go
Assumes that #265 and #266 are merged.
=> Release 0.43.1

input/system/heroku/logs.go
This is a bug that was introduced in the refactoring in
735d95cc4e6d4ab012a2a5a92bc282bd180c2fb1, which kept the old logic that
remembers log lines across processing iterations. That is no longer needed
since we now handle that the same way for all streamed log providers in
setupLogStreamer.
=> Heroku log processing: Avoid repeating the same line over and over again

input/system/selfhosted/logs.go
Signal the wait group passed to the log transform setup once the context is canceled.
=> Improve shutdown handling

input/postgres/relation_stats.go
In the case I have a following table setup:
```
parent_table (oid 1)
child_table1 (oid 2)
child_table2 (oid 3)
```
When `child_table2` is the relation targeted by the lock (in the list of `locked_relids`), the `relationStatsSQL` query will be blocked because of the following part of the query:
```sql
SELECT pg_catalog.sum(pg_catalog.pg_table_size(inhrelid))
FROM pg_catalog.pg_inherits
WHERE inhparent = 1 --- parent_table's oid is 1
```
This will try to get the table size of oid 3 (`child_table2`), therefore it'll be blocked.
With this PR, if oid 3 is in `locked_relids`, add parent (oid 1) to the "ignore list" so that we won't make the query like above.
=> Avoid getting locked when collecting the relation stats with child tables

runner/logs.go
Previously we kept logs around after the grant or upload failed, but this actually causes more trouble in situations where the upstream server is not available. In such situations the collector will try reprocessing more and more data until the server accepts data again, or the collector crashes.
Since we already have HTTP client retries enabled since 314edc86e90b1f584c364b8665c42c3e643f2d86, rely on that to workaround transient failures, and otherwise discard the logs. This is is similar to log downloads where we also discard logs if we can't send them (after the HTTP retry limit is reached).
=> Log streaming: Discard logs after consistent failures to upload

CHANGELOG.md, contrib/helm/pganalyze-collector/Chart.yaml, packages/Makefile, util/version.go
I may want to add https://github.com/pganalyze/collector/pull/329 too in this release
=> Release 0.46.0

runner/diff.go
Bugfix: Use the current stats value as a diff-ed value when the previous state is not found for no diff required values
When we introduced some new values for relation and database stats, we forgot to address these cases. Stats data is using lots of diff-ed values (aka previous values are required), but some of the values, we're just passing the current value.
We need to make sure to initialize these stats with the current value if no previous value is found, to avoid the value falsely becoming 0.
=> Address the case when the previous state is not found

CONTRIBUTING.md, packages/Makefile, packages/repo/Dockerfile.repo-rpm, packages/repo/Makefile
=> Package repo sync: Use assets built by GH actions & other improvements

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/release.yml, .github/workflows/test-packages.yml
- Update GitHub action actions/checkout to v3
- Update CodeQL analysis to v2
See warnings in the action run output, e.g.,
https://github.com/pganalyze/collector/actions/runs/4615818101
=> Update GitHub actions

input/system/azure/logs.go
Because of the way the goroutine functions close over the loop
variable, every goroutine would likely process the last partition.
Raised by go vet.
Pass the variable as a parameter of the functions.
=> Fix partition selection issue in Azure log processing

integration_test/Dockerfile.test-citus, integration_test/Dockerfile.test-pg10, integration_test/Dockerfile.test-pg11, integration_test/Dockerfile.test-pg12, integration_test/Dockerfile.test-pg13, integration_test/Dockerfile.test-pg14, integration_test/Dockerfile.test-pg15, integration_test/Dockerfile.test-pg16, integration_test/Makefile, integration_test/pg16.expected
=> Integration tests: Fix locale errors, add PG16, update Citus

config/read.go, runner/logs.go
Trying to detect some common mistakes of the collector setup and log something useful.
=> Add helpful logs for some common mistakes

CHANGELOG.md, contrib/helm/pganalyze-collector/Chart.yaml, packages/Makefile, util/version.go
Blocked by https://github.com/pganalyze/collector/pull/484 (we should make a release after this gets merged)
=> Release 0.52.3

CHANGELOG.md, contrib/helm/pganalyze-collector/Chart.yaml, packages/Makefile, util/version.go
Likely this will be the final release of 2023
=> Release 0.52.4

input/system/tembo/system.go
Fixes collector crash when metrics result is empty. Also adds error handling to relevant functions.
=> Tembo System: Check for Empty Metrics Result

CHANGELOG.md, contrib/helm/pganalyze-collector/Chart.yaml, packages/Makefile, util/version.go
This will be the first release with Helm chart CI release, let's see if it goes well (or not).
=> Release 0.56.0

contrib/install.sh, packages/repo/sync_deb.sh, packages/test/Makefile
See also https://github.com/pganalyze/pganalyze-docs/pull/259
=> Add Ubuntu 24.04

CHANGELOG.md, contrib/helm/pganalyze-collector/Chart.yaml, packages/Makefile, util/version.go
I think we have enough changes to make a new release
=> Release 0.57.0

README.md, contrib/helm/pganalyze-collector/values.yaml
We will be making this change in docs (PR incoming, the former PR is https://github.com/pganalyze/pganalyze-docs/pull/260), so let's make sure that the collector docs align it too.
=> Use true instead of 1 as the config setting examples

runner/generate_helper_sql.go
Pair PR to https://github.com/pganalyze/pganalyze-docs/pull/287
=> Update helper setup to use DROP FUNCTION IF EXISTS

packages/repo/sync_deb.sh
This asks for confirmation which we don't want in the automated flow.
=> Debian package build: Allow override of public key file

input/system/azure/system.go
https://sentry.io/issues/5910271246
=> Improve error handling for Azure system stats

README.md
=> README: fix bad iam policy link

.gitignore, Makefile
Automatically vendor protoc if the correct version is not found in
PATH (or not already vendored).
=> Automatically vendor protoc if not found

input/postgres/plans.go
The `aurora_stat_plans` function utilizes `pg_stat_statements` under the covers. Minor version 11 of the extension that shipped with PG17 modified some of the IO columns which was accounted for in #526. With PG17 now available in AWS Aurora, this is necessary.
=> Initial changes to support Postgres 17 on Aurora and the updated aurora_stat_plans function

CONTRIBUTING.md
It's been a while since I last did the release and as I try to remember small bits of the release step, I figured that it'd be the best to document.
=> Add more details to the release step
