- contrib/systemd/pganalyze-collector.service
> FIX: SystemD will not restart a crashed collector daemon 

- config/read.go
- util/awsutil/amazon.go
I got an interesting error while trying to setup the pganalyze collector in an aws ecs service backed by fargate:
```
2019/07/16 13:24:33 E [default] Rds/Logs: Could not find RDS instance: NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, .
CredentialsEndpointError: failed to load credentials
caused by: RequestError: send request failed
caused by: Get http://169.254.170.2/v2/credentials/abcdef12-3456-789a-bcde-f1234567: Unencrypted connection is not permitted by pganalyze configuration
```
ECS tasks using a slightly different metadata endpoint which should probably also be whitelisted. I've pushed a custom docker image with this new code and it works great. Sorry, I …
> Fix ecs credentials

- .travis.yml
- integration_test/Dockerfile.test-pg10
- integration_test/Dockerfile.test-pg11
- integration_test/Dockerfile.test-pg12
- integration_test/Dockerfile.test-pg13
- integration_test/Dockerfile.test-pg92
- integration_test/Dockerfile.test-pg93
- integration_test/Dockerfile.test-pg94
- integration_test/Dockerfile.test-pg95
- integration_test/Dockerfile.test-pg96
- packages/src/Dockerfile.build.deb-systemd
- packages/src/Dockerfile.build.deb-upstart
- packages/src/Dockerfile.build.rpm-systemd
- packages/src/Dockerfile.build.rpm-sysvinit
See https://github.com/golang/go/issues/37436 which was causing
"mlock of signal stack failed: 12" on Ubuntu systems.
> Use Golang 1.14.3 patch release

- input/full.go
- input/postgres/schema.go
There are a set of error messages (now changed to warnings), that are
acceptable in some cases, and don't stop the data being sent. Clarify
the messages to be clear that only some data is missing, and being skipped.
> Improve non-fatal error message to clarify the collector still works

- contrib/pganalyze-collector.conf
This improves the chance that this is set up correctly from the
beginning, without requiring a backwards incompatible change in the
collector.
> Example collector config: Use collect all databases option in the example

- input/postgres/buffercache.go
- input/postgres/statements.go
This is more correct going forward (see https://blog.golang.org/go1.13-errors), and adds a required type check for the error type, since the database methods can also return net.OpError.
Fixes "panic: interface conversion: error is *net.OpError, not *pq.Error" crashes.
> Handle Postgres error checks using Go 1.13 error helpers

- config/config.go
- config/read.go
- input/postgres/buffercache.go
- input/postgres/functions.go
- input/postgres/relation_bloat.go
- input/postgres/relation_stats.go
- input/postgres/relation_stats_ext.go
- input/postgres/relations.go
- input/postgres/schema.go
- input/postgres/vacuum_progress.go
- input/postgres/vacuum_stats.go
- integration_test/Makefile
- output/transform/activity.go
- reports/bloat.go
- reports/buffercache.go
- reports/vacuum.go
- runner/activity.go
This is like `ignore_table_pattern`, but pushed down into the actual
stats-gathering queries to improve performance. This should work much
better on very large schemas.
We use a regular expression instead of the current glob-like matching
since the former is natively supported in Postgres.
Open items:
> Add ignore_schema_regexp

- output/compact_logs.go
- output/transform/logs.go
Whilst not recommended, in some scenarios changing the log_line_prefix
is difficult, and we want to make it easy to get EXPLAIN data even in
those scenarios.
In case the log_line_prefix is missing the database (%d) and/or the user
(%u), we simply use the user and database of the collector connection.
> EXPLAIN plans / Query samples: Support log line prefix without %d and %u

- input/logs.go
- input/postgres/explain.go
- logs/stream/stream.go
- runner/logs.go
Totally untested so far but it builds and doesn't break existing tests.
Fixes #910
> Enable log explain for all databases

- config/config.go
- config/read.go
- input/full.go
- input/postgres/statements.go
- output/transform/activity.go
- output/transform/logs.go
- output/transform/postgres_query.go
- runner/queries.go
- util/normalize.go
By default we replace everything with `<unparsable query>` (renamed from the previous `<truncated query>` for clarity), to avoid leaking sensitive data that may be contained in query texts that couldn't be parsed and that Postgres itself doesn't mask correctly (e.g. utility statements).
However in some situations it may be desirable to have the original query texts instead, e.g. when the collector parser is outdated (right now the parser is Postgres version 10, and some newer Postgres 12 query syntax fails to parse).
To support this use case, a new `filter_query_text` / `FILTER_QUERY_TEXT` option is introduced which can be set to "none" to keep all query texts.
> Allow keeping of unparsable query texts as an optional setting

- input/postgres/relation_stats.go
- input/postgres/relations.go
This fixes two situations:
- Tables being rewritten would cause the relation statistics query to
fail due to statement timeout (caused by lock being held)
- Non-relation locks held in AccessExclusiveLock mode would cause all
relation information to disappear, but only for everything thats not
the top-level relation information. This is due to the behaviour of
NOT IN when the list contains NULLs (never being true, even if an
item doesn't match the list). The top-level relation information
was using a LEFT JOIN that doesn't suffer from this problem. This likely
caused problems reported as missing index information, or indices
showing as being recently created even though they've existed for a
while.
> Locked relations: Ignore table statistics, handle other exclusive locks

- README.md
- input/postgres/explain.go
This works with the big caveat that more queries may contain semicolons than we expected: I was testing by submitting queries in psql, and things there need to end in a semicolon. That's probably not a common use case, but a lot of larger heredoc-style queries embedded in apps often end in semicolons out of habit. Should we strip trailing semicolons? Trailing semicolons and whitespace? ~Or is that all stripped out via `pg_query.Parse`?~ I realize it's *not* stripped out because that's exactly what I ran into it. I'll try to regexp_replace it.
This will also need docs, but this part should probably come first.
> Use helper function for log-based EXPLAIN access if available

- input/postgres/schema.go
- output/transform/postgres_functions.go
- output/transform/postgres_relations.go
- runner/diff.go
- state/state.go
- state/util.go
Relation oids are not necessarily unique across databases, but we
assume they are, which can cause issues where we clobber some relation
references in our mapping.
Track the mapping per-database instead to avoid this.
~We may need to take a similar approach to other database objects, but I
think a similar pattern should work.~ (I don't think any other code paths are
affected--see below).
I've now tried this in dev and I can't think of a good way to test the issue this
is intended to fix, but it does not break anything.
> Fix oid aliasing when constructing snapshot

- input/postgres/schema.go
- input/postgres/superuser.go
This avoids collecting data from these internal databases, which produces
unnecessary errors when using the all databases setting.
> Ignore internal admin databases for GCP and Azure

- output/transform/postgres_relations.go
It can occur that we don't have statistics for a relation, when a lock is held on the relation. This situation wasn't handled correctly in the output logic, leading to a collector crash.
> Schema stats handling: Avoid nil pointer dereference

- config/config.go
- config/read.go
- util/awsutil/amazon.go
Set the role to be assumed using the new "aws_assume_role" / AWS_ASSUME_ROLE
configuration setting. This is useful when the collector runs in a different
AWS account than your database.
See https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html
> Add support for assuming instance roles

- input/postgres/helpers.go
- input/system/google_cloudsql/log_receiver.go
- input/system/google_cloudsql/test_run.go
- runner/logs.go
This lets us ensure we have a valid prefix on all platforms.
> Hoist log_line_prefix check in logs test

- input/system/selfhosted/log_receiver.go
- logs/stream/stream.go
- logs/stream/stream_test.go
```
Self-managed server: Process logs every 3 seconds, instead of on-demand
This reduces the amount of overall log snapshots generated, and also
helps with the overall efficiency of the code if there are many lines
that are not ready yet (the typical case on a busy system).
```
```
Log stream: Optimize stitching logic to allocate one large string
Previously we kept resizing the string, leading to many small allocations.
Since we have all the strings that we need already allocated, instead do
one new allocation once, for the final size of the string.
Note that there is further optimization potential here, but this aims to
reduce the biggest current problem point.
```
```
Log stream: Handle streams with missing PID/timestamps/etc correctly
Previously we would sort lines by PID, even when …
```
> Self-managed server log tail: Speed improvements, handle multi-line logs correctly

- main.go
- runner/full.go
Add the collector version and the Postgres version of every monitored
server to collector test output. This makes it easier to diagnose
customer issues if they report collector test problems, since both of
the above are often very useful in debugging issues.
Output is now like this:
```
2020/10/20 17:52:02 I Running collector test with pganalyze-collector 0.33.1
2020/10/20 17:52:02 I [server1] Testing statistics collection...
2020/10/20 17:52:04 I [server1]   Test collection successful for PostgreSQL 11.9 (Ubuntu 11.9-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0, 64-bit
2020/10/20 17:52:06 I [server1]   Test submission successful (1.34 MB received, server 6ayj3psrubag7gwuzv7sbwnq7a)
2020/10/20 17:52:06 I [server1] Testing activity snapshots... …
```
> Improve self-test output

- runner/full.go
These panics are by definitions things that should not happen, so
having more context as to why they happened is always useful.
> Change panic stack trace logging from Verbose to Warning

- logs/stream/stream.go
- state/logs.go
We've previously relied on Go's finalizer logic to close the file handle
after the associated object expired, but this can cause problems with
keeping files around for too long, even after they are already deleted.
This changes the logic to instead close the temporary files right before
they are deleted. It also fixes one instance where we possibly didn't
clean up files, though in practice this is unlikely to have occurred.
> Log processing: Explicitly close temporary files

- logs/validate_config.go
We do not parse logs correctly when this is configured, and there's
little reason to have this since Log Insights does this for you.
> Disable log collectiong with setting log_error_verbosity=verbose

- input/system/selfhosted/log_receiver.go
Right now, we print errors only after the loop completes, but the loop
never completes because the existing control flow prevents that.
Instead, break from the loop when the context closes and print the
error, if any. Also avoid redundant Close calls that already happen
with the defer we have in place.
Noticed this when investigating a support issue.
> Fix log tailing error printing logic

- state/logs.go
Due to the change in dc4a65638c2d169af90c224cf9ee2300fa88f491 we may
enter cleanup in cases where the TmpFile wasn't actually initialized.
In such cases, we should just do nothing in cleanup.
> Log file cleanup: Only delete temporary file if it was created

- .github/workflows/ci.yml
- .github/workflows/release.yml
- integration_test/Dockerfile.test-pg10
- integration_test/Dockerfile.test-pg11
- integration_test/Dockerfile.test-pg12
- integration_test/Dockerfile.test-pg13
- integration_test/Dockerfile.test-pg92
- integration_test/Dockerfile.test-pg93
- integration_test/Dockerfile.test-pg94
- integration_test/Dockerfile.test-pg95
- integration_test/Dockerfile.test-pg96
- packages/src/Dockerfile.build.deb-systemd
- packages/src/Dockerfile.build.deb-upstart
- packages/src/Dockerfile.build.rpm-systemd
- packages/src/Dockerfile.build.rpm-sysvinit
Note that we can't upgrade to Go 1.15 for now due to https://github.com/golang/go/issues/39568 (which will need some special attention to avoid breaking integrations)
> Package builds: Use Golang 1.14.11 patch release

- README.md
I noticed that the [instructions on pganalyze.com][1] recommend the explicit public schema when
creating the `pg_stat_statements` extension, but this README does not. Makes sense for them to be
consistent?
Also, probably makes sense to do the same for `pg_buffercache`?
[1]: https://pganalyze.com/docs/install/amazon_rds/02_create_monitoring_user
> Update docs on CREATE EXTENSION to match website

- .github/workflows/ci.yml
- packages/src/deb-systemd/after-install.sh
- packages/src/deb-upstart/after-install.sh
- packages/src/deb-upstart/after-upgrade.sh
This gives it permission to read Postgres log files in a default
install, simplifying Log Insights setup.
The adm group according to the Debian wiki [1]:
Group adm is used for system monitoring tasks. Members of this
group can read many log files in /var/log, and can use xconsole
[1]: https://wiki.debian.org/SystemGroups
> Add pganalyze system user to adm group in Debian/Ubuntu packages

- logs/parse.go
- runner/logs.go
This also fixes a related problem with the log_line_prefix check erroring
out, which we can ignore since the Heroku log_line_prefix is special
cased and not handled in the regular logic.
> Don't run log test for Heroku, instead provide info message

- config/config.go
- config/read.go
- input/full.go
- input/postgres/replication.go
- input/postgres/settings.go
- input/postgres/version.go
- input/system/heroku/log_receiver.go
- main.go
- runner/activity.go
- runner/full.go
- runner/queries.go
- state/errors.go
- state/state.go
This allows users to configure the collector in a no-op mode on
replicas (we only query if the monitored database is a replica), and
automatically switch to active monitoring when the database is no
longer a replica.
> Add a skip_if_replica / SKIP_IF_REPLICA option

- input/postgres/vacuum_progress.go
Before this was failing with an error because we couldn't determine
the relation and namespace name correctly. Without access to the
pg_stat_progress_vacuum table this is not possible to do reliably, so
skip manual vacuums instead in that situation.
Fixes #113
> Ignore manual vacuums if we can't access pg_stat_progress_vacuum

- input/postgres/statements.go
There is no way to correctly diff these kinds of queries, because Postgres
will report one entry for each query, but won't let us see the text or
the queryid.
For Postgres 10 and newer, the pg_monitor role should be used, which
avoids this problem altogether. On older Postgres releases, we only
support monitoring a single role (that which owns the monitoring helper
function).
> pg_stat_statements: Ignore "insufficient privilege" queries w/o queryid

- setup/state/state.go
We intend to ignore errors reporting setup progress, but we do need to
short-circuit when there *is* an error.
> Fix error handling if last guided setup step fails

- input/system/google_cloudsql/log_receiver.go
- input/system/selfhosted/log_receiver.go
- logs/stream/stream.go
Right now, log streams for GCP (via Pub/Sub) and self-hosted systems
(via local file tails) strip trailing newlines, which can lead to
issues parsing some multi-line queries for log-based EXPLAIN when
those newlines are semantically significant.
One known issue is for single-line comments. A query like this:
SELECT now() -- current timestamp
, a FROM my_table
would be parsed as
SELECT now() -- current timestamp   , a FROM my_table
which is a different query entirely. This can lead to an incorrect
EXPLAIN plan being generated, or (more likely) failure to generate a
plan entirely due to broken syntax or an incorrect number of
parameters.
Note that RDS and Heroku Postgres log processing does not have this
issue. Azure will be verified separately.
> Restore trailing newlines for GCP and self-hosted log streams

- config/config.go
- config/read.go
Right now, we do not validate it, so if set to an invalid URL, it can
crash some of our helper functions with a segfault due to a nil
pointer reference.
Validate at startup, but allow to continue to avoid retrofitting error
handling across helpers that right now cannot return errors. The helpers
return dummy/default values which will fail authentication.
See #124 (this is not a fix for that, since go-ini does not parse
comments correctly, but at least it will give users a proper error
message instead of a segfault.
> Validate db_url/DB_URL, if set, when initially reading config

- input/postgres/statements.go
- output/transform/activity.go
- output/transform/logs.go
- output/transform/postgres_query.go
- runner/activity.go
- state/activity.go
- util/normalize.go
When a query is cutoff due to pg_stat_activity limit being reached,
instead of showing `<unparsable query>`, show `<truncated query>`, to make
it clear that increasing track_activity_query_size would solve the issue.
> Normalize query: Keep using "<truncated query>" for pg_stat_activity

- input/postgres/explain.go
- input/postgres/statements.go
- util/is_utility.go
- util/is_utility_test.go
These are bogus right now due to Aurora bugs, so zero them out to avoid distorting our graphs.
Strictly speaking, I think we've only seen `blk_read_time` and `blk_write_time` being off, ~but it's probably prudent to ignore all of them~ (we've reviewed the other stats and feel it's better to only ignore timing, since that may be handled as an Aurora extension whereas other stats are likely straight from Postgres). Also, since these are not nullable, I'm instead zeroing them out. I think this is better than the impossibly huge values we're seeing now, but let me know if you think we should approach this differently.
> Triage Aurora utility statement I/O stats issue

- output/transform/postgres_query.go
- output/transform/postgres_statements.go
- state/postgres_statement.go
Right now, if pg_stat_statements.max is too low for a given query
workload, we may end up capturing stats for queries whose text is no
longer available to us. We flag this situation by using the string
`<unidentified queryid>` as the query text, but this is fairly opaque.
We have a change in progress to improve the display of this in-app,
but changing the actual marker string used here can help clarify
things as well.
Instead of `<unidentified queryid>`, this patch changes the text for
queries like this to `<query text unavailable>`, which describes the
situation more accurately.
> Change <unidentified queryid> marker to clarify cause

- input/postgres/schema.go
If a database is specified multiple times via dbname, we collect its
schema information multiple times, but fail to correctly assemble a
snapshot due to identified collisions. The inconsistent snapshots are
sent off correctly, but can cause problems when processing.
Instead, only collect each database once to avoid the issue.
We could potentially warn when this happens, but the intent is clear
so being overparticular here seems of little benefit.
> Ignore duplicate dbnames when collecting

- packages/src/Dockerfile.build.deb-systemd
We missed this in the original guided setup patch. The program is
there if building from source, but not actually bundled into our
packages.
> Include guided setup in systemd-flavored deb package build

- config/read.go
Right now, if the pganalyze section is missing, we ignore this issue
and proceed with an empty api_key (and default api_base_url). If
there's a typo in the section name or a config structure issue (e.g.,
API key in the default section instead of the pganalyze section), it
can be hard to figure out why an API key is being rejected.
Instead, fail fast when reading the config if the [pganalyze] section
is missing or cannot be mapped onto the config struct.
> Fail fast when pganalyze section is missing in config file

- config/config.go
- config/read.go
- go.mod
- go.sum
- input/system/heroku/log_receiver.go
- input/system/selfhosted/log_receiver.go
- input/system/selfhosted/syslog_log_receiver.go
- logs/parse.go
- logs/parse_test.go
- logs/stream/stream.go
- main.go
- runner/logs.go
- state/logs.go
- vendor/gopkg.in/mcuadros/go-syslog.v2/.travis.yml
- vendor/gopkg.in/mcuadros/go-syslog.v2/LICENSE
- vendor/gopkg.in/mcuadros/go-syslog.v2/README.md
- vendor/gopkg.in/mcuadros/go-syslog.v2/doc.go
- vendor/gopkg.in/mcuadros/go-syslog.v2/format/automatic.go
- vendor/gopkg.in/mcuadros/go-syslog.v2/format/format.go
- vendor/gopkg.in/mcuadros/go-syslog.v2/format/rfc3164.go
- vendor/gopkg.in/mcuadros/go-syslog.v2/format/rfc5424.go
- vendor/gopkg.in/mcuadros/go-syslog.v2/format/rfc6587.go
- vendor/gopkg.in/mcuadros/go-syslog.v2/handler.go
- vendor/gopkg.in/mcuadros/go-syslog.v2/internal/syslogparser/LICENSE
- vendor/gopkg.in/mcuadros/go-syslog.v2/internal/syslogparser/README.md
- vendor/gopkg.in/mcuadros/go-syslog.v2/internal/syslogparser/rfc3164/rfc3164.go
- vendor/gopkg.in/mcuadros/go-syslog.v2/internal/syslogparser/rfc5424/rfc5424.go
- vendor/gopkg.in/mcuadros/go-syslog.v2/internal/syslogparser/syslogparser.go
- vendor/gopkg.in/mcuadros/go-syslog.v2/server.go
- vendor/modules.txt
```
Add support for receiving logs from remote servers over syslog
You can now specify the new "db_log_syslog_server" config setting, or
"LOG_SYSLOG_SERVER" environment variable in order to setup the collector
as a syslog server that can receive logs from a remote server via syslog
to the server that runs the collector.
Note that the format of this setting is "listen_address:port", and its
recommended to use a high port number to avoid running the collector as root.
For example, you can specify "0.0.0.0:32514" and then send syslog messages
to the collector's server address at port 32514.
Note that you need to use protocol RFC5424, with an unencrypted TCP
connection. Due to syslog not being an authenticated protocol it is
recommended to only use this integration over private networks.
``` …
> Add support for remote syslog

- input/system/selfhosted/log_receiver.go
Some Postgres installations are configured to log both standard-format
log files and CSV log files to the same directory, but the collector
currently reads all files specified in a db_log_location, which works
poorly with this setup.
Since we already ignore some files (zipped log files), and we do not
support parsing CSV files, add CSV log files to the ignore list.
Fixes #83
> Ignore CSV log files

- contrib/pganalyze-collector.conf
- integration_test/guided-setup.collector-config.nopass.expected
* put db_host first since this is arguably most important
* drop port because this is almost always 5432 and an example is
still available in the second, fuller, commented-out config
> Tweak collector sample config file

- helper/main.go
- input/system/selfhosted/log_receiver.go
The helper fails on a default AL2 install since the binary is called
postmaster not postgres, and there's no apparent reason not to use the
GUCS directly. This lets us drop the helper subcommand entirely.
Also, do not show a db_log_location if the log directory is inside the
data directory: this is almost certain to cause permissions problems,
and instead we can direct users to address this in our setup guide.
> Update log location discovery

- input/postgres/statements.go
Right now, we require the pg_stat_statements extension to be installed
in the public schema, and try to create it if it does not exist.
However, we only look for it in the public schema, and run the create
with IF NOT EXISTS, which will be a no-op if it does exist in a
different schema. At this point, assuming we created it successfully,
we'll try to query pg_stat_statements again, and get a confusing
"pg_stat_statements does not exist" message.
Instead, check to see if the extension exists in another schema first,
and give a more appropriate error message.
> Check whether pg_stat_statements exists in a different schema

- logs/emit_test_lines.go
The marker means the resulting query gets hidden from the EXPLAIN plan
list, which is what we don't want for this test query - its intentional
that we can see the EXPLAIN plan we're generating for the test.
> Don't use pganalyze query marker for "--test-explain" command

- packages/src/Dockerfile.build.deb-systemd
- packages/test/Makefile
This avoids making the build more complicated, because the upstream Go
binaries are no longer compatible with older GCC releases, such as the
one used on Debian Jessie.
> Packages: Remove support for Debian Jessie (no longer supported)

- .github/workflows/ci.yml
- contrib/install.sh
- integration_test/Makefile
- packages/repo/Makefile
Add a one-step install script for the collector. This lets us simplify package installation instructions to something like
```
curl https://packages.pganalyze.com/collector-install.sh | bash
```
This uses sudo (prompting if necessary) if not already running as root and will install the correct package based on system type. If an unrecognized version of a supported distribution is detected, we prompt whether the user would like to install the latest available package for that distribution instead.
The script supports several environment variables:
- `PGA_INSTALL_NONINTERACTIVE`: if non-empty, do not prompt for user input and assume `y` to all prompts
- `PGA_API_BASEURL`: if non-empty, api_base_url to add to collector config as part of install
- `PGA_API_KEY`: if non-empty, pganalyze API …
> Add curl-able install script to streamline installation across systems

- config/read.go
- util/awsutil/amazon.go
Previously we were re-using our shared HTTP client, which has a rather
high timeout (120 seconds) that causes the HTTP client to wait around
for a long time. This is generally intentional (since it includes the
time spent downloading a request body), but is a bad idea when running
into EC2's IDMSv2 service that has a network-hop based limit. If that
hop limit is exceeded, the requests just go to nowhere, causing the
client to wait for a multiple of 120 seconds (~10 minutes were observed).
This instead uses a special client for the EC2 instance metadata service
that has a much lower timeout (1 second, like in the AWS SDK itself), to
avoid the problem.
See also https://github.com/aws/aws-sdk-go/issues/2972
> Reduce timeout for accessing EC2 instance metadata service

- contrib/install.sh
Right now, we allow curl output to go to stdout, which means the
sudo prompt may be sandwiched between two different sets of curl output:
```
$ curl https://packages.pganalyze.com/collector-install.sh | env PGA_API_KEY=... PGA_GUIDED_SETUP=true bash
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  5652  100  5652    0     0   8499      0 --:--:-- --:--:-- --:--:--  8512
This script requires superuser access to install packages
You may be prompted for your password by sudo
[sudo] password for maciek:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  1625  100  1625    0     0   4737      0 --:--:-- --:--:-- --:--:--  4723
```
This is …
> Use curl -s when fetching signing keys for debs

- Dockerfile
- Makefile
Alpine has a very small stack size by default (80kb) which is less than
the default that Postgres expects (100kb). Since there is no good reason
to reduce it to such a small amount, increase to usually common Linux
default of 2MB stack size.
This would have surfaced as a hard crash of the Docker container with
error code 137 or 139, easily confused with out of memory errors, but
clearly distinct from it.
> Docker builds: Increase stack size to 2MB to prevent rare crashes

- helper/main.go
Right now, the helper program we use for some lookups assumes the
Postgres process is named "postgres". This is true in most situations,
but on some systems (notably RHEL), the process is instead named
"postmaster", so we may fail to find it.
To work around this, look for "postgres" first but fall back to
"postmaster" if that fails.
Tested locally by inverting the order of the lookups.
> Also check for the name "postmaster" when looking for Postgres pid

- input/postgres/settings.go
This can contain sensitive information (full connection string to the
primary), and pganalyze does not do anything with it right now. In the
future, we may partially redact this and use primary hostname
information, but for now, just fully redact it.
> Redact primary_conninfo setting if present and readable

- input/system/selfhosted/log_receiver.go
We still output a warning in this case, but there are legitimate use cases
where someone uses a different local IP address than 127.0.0.1 and wants
to discover the log directory.
> Selfhosted: Support running log discovery with non-localhost db_host settings

- Dockerfile
- contrib/docker-entrypoint.sh
This enables the collector container to run in environments that require the
whole container to run as a non-root user, which previously was not the case.
For compatibility reasons the container can still be run as root explicitly,
in which case the setpriv command is used to drop privileges. setpriv replaces
gosu since its available for installation in most distributions directly, and
fulfills the same purpose here.
---
**Docker tag:** ```docker pull quay.io/pganalyze/collector:hotfix-docker-user```
> Docker: Use Docker's USER command to set user, to support running as non-root

- integration_test/Dockerfile.test-guided-setup
- integration_test/Dockerfile.test-pg10
- integration_test/Dockerfile.test-pg11
- integration_test/Dockerfile.test-pg12
- integration_test/Dockerfile.test-pg13
- integration_test/Dockerfile.test-pg93
- integration_test/Dockerfile.test-pg94
- integration_test/Dockerfile.test-pg95
- integration_test/Dockerfile.test-pg96
- packages/src/Dockerfile.build.deb-systemd
- packages/src/Dockerfile.build.rpm-systemd
Looks like upstream has stopped supporting the storage.googleapis.com
URLs, lets use the URL of the official download page instead.
> Update URLs for Go binary downloads in integration_test/packages

- output/transform/postgres_replication.go
This was previously not setting the StandbyIdx on the statistics values
for replication followers, causing all statistics to incorrectly be
associated to the first follower (since 0 is the default for the field).
> Output transform: Correctly report index for replication statistics

- contrib/install.sh
Assume we can treat it exactly like RHEL and install those packages.
Tried copying the script to a CentOS 7 instance, where the problem was
originally reported, and the collector installs fine with these
changes.
> Add support for CentOS to install script

- input/postgres/explain.go
This previously discarded those samples by accident, instead of returning
them with the result (without running EXPLAIN again).
> Query samples: Keep auto_explain samples when log-based EXPLAIN is on

- input/postgres/relation_stats_ext.go
This typo was causing failure for pganalyze table stats when used on DBs with citus extension enabled.
New release would be appreciated with this fix in, we can't see any stats in pganalyze due to this issue.
> Fix citus relation stats sql query typo

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .gitignore
- Makefile
Since there isn't an easy way to keep us all on the same version of protobuf/protoc, I wrote a semi-automated script to do that for us.
Here's what you see when there's a version mismatch:
>⚠️  protoc version needed: 3.14.0 vs none installed
>ℹ️  Please download the correct protobuf binary for your OS from https://github.com/protocolbuffers/protobuf/releases/tag/v3.14.0
>ℹ️  Note the download's name will look like this: protoc-3.14.0-osx-x86_64.zip
>ℹ️  Copy the unzipped folder into this project, and rename it to "protoc"
>ℹ️  If this is macOS, you will need to try running the binary yourself, then go to Security & Privacy to explicitly allow it.
> Vendor protoc to keep the version consistent

- output/transform/activity.go
- output/transform/logs.go
- output/transform/util.go
This previously used a simplistic model where we assumed we only ever
have one vacuum run referencing a certain table. However this is not
correct when the TOAST relation of a table is being vacuumed at the same
time as the table itself. In that case we'll have the same relation twice,
requiring the use of the more correct upsertRelationReference helper.
In passing, move the upsert helper functions into a combined util.go file.
> Vacuum activity: Correctly handle output transform of duplicate tables

- input/postgres/schema.go
If we fail to collect schema metadata, a database can remain
permanently hidden and a lot of in-app functionality does not
work. Since verbose logs are not likely to be turned on for a running
collector, hiding this message makes this situation difficult to
discover.
Elevate the message to a warning.
> Change schema collection message to warning

- logs/parse.go
- logs/parse_test.go
This adds the following `log_line_prefix` supported settings:
* `log_line_prefix = '%p-%s-%c-%l-%h-%u-%d-%m '`
* `log_line_prefix = '%m [%p][%b][%v][%x] %q[user=%u,db=%d,app=%a] '`
> Add two additional log_line_prefix settings per request

- logs/analyze.go
- logs/analyze_test.go
This is a variant of the existing invalid input syntax log event, with
a few additional details.
> Log Insights: Add "invalid input syntax for type json" log event

- logs/analyze.go
- logs/analyze_test.go
Previously we did not support a double quote showing up inside the array
content, and would instead detect the rest of the log line as unknown
data. This adjusts the regexp to correctly capture that data and mark
it as a table data log secret.
Additionally, adds the known DETAIL line "Unexpected array element.".
> Log Insights: Improve regexp for "malformed array literal" log event

- output/transform/postgres_relations.go
- state/util.go
Previously we would sometimes use 0 in these situations, which is a valid
index when referencing the very first table in the list.
Note that whilst its not always clear why bad references here happen, as
they should only happen when the schema_table_regexp logic is active,
its better to not send bogus data to the server.
> Table processing: Ensure we use -1 index for unknown parent/FK tables

- runner/logs.go
Since this also occurs as output after a successful regular test, it
contradicts our in-app instructions to wait until real snapshot data
comes in to proceed with Log Insights setup.
Since Heroku setup is generally straightforward, proceeding
optimistically here does not save much time and may make it harder to
diagnose issues if there is a problem, so drop these instructions.
> Drop Log Insights instructions after Heroku log test

- input/system/rds/logs.go
- util/awsutil/rds.go
- util/ttl_map.go
`FindRdsInstance` is being called 21 times every 10 minutes (once for the full snapshot, once every 30 seconds for log snapshots), which is an issue for customers with many servers.
This PR caches the API requests for log snapshots only, with a TTL of 5 minutes. This should bring us down to 3 requests every 10 minutes.
Edit: this now also caches API errors so we will pause this API request for 10 minutes if there is an outage / a server is being reprovisioned.
> Cache RDS server IDs to reduce API requests

- Makefile
See https://unix.stackexchange.com/questions/85249/why-not-use-which-what-to-use-then
> Makefile: Use "command -v" instead of "which" to check for protoc

- Dockerfile
This change reduces the build time and reduces the runtime image size from 620mb to 38mb(updated these values as i had accidentally built the -original image initially off of an edit i had made. this is now the diff in build size/time from what's currently in master)
with changes
```
-> % docker build . -t pgcollector
[+] Building 63.9s (19/19) FINISHED                                                                                                                       
=> [internal] load build definition from Dockerfile                                                                                                 0.0s
=> => transferring dockerfile: 1.18kB                                                                                                               0.0s
=> [internal] load …
```
> Reduce build time and use slim image

- Makefile
This utilizes Docker's manifest handling to contain both architectures
within the same Docker tag.
In passing improve the Makefile task and rename it to "docker_release"
for clarity.
> Build multi-arch Docker image for x86/amd64 and ARM64

- logs/analyze.go
This was an oversight in an already quite extensive list of different
database objects in Postgres.
> Log Insights: Add regexp match for "permission denied for table" event

- logs/parse.go
- logs/parse_test.go
Previously we supported handling timezone values in three cases:
(1) No timezone specified
(2) UTC/GMT timezone explicitly specified
(3) Timezone specified that matches the collector system timezone
However we did not handle a log_timezone setting that is different from
the timezone thats configured on the system the collector is running on.
This was caused by incorrect assumptions of what time.Parse() does in
this case. As we have no other way to get the UTC timestamp of a logline,
we rely on the system's timezone database to help us parse the log line
in the correct timezone for this edge case.
> Log processing: Handle non-UTC/non-local log_timezone values correctly

- input/system/heroku/log_receiver.go
Heroku total memory used to exclude free memory, but at some point it
looks like this was changed, so we are now overcounting total memory
by the amount of free memory available.
Exclude free memory from the total memory number.
> Do not count free memory in total memory on Heroku

- config/read.go
Right now, we parse boolean values in our config files with go-ini,
but environment-based config goes through some ad-hoc parsing. For
most boolean values, any value other than the empty string and '0' is
considered true (for the DB_ALL_NAMES setting, any value except '1' is
considered false).
Unify this to treat case-insensitive false, off, no, 'f', and 'n' as
false in addition to zero. All other values are still considered true
to preserve backward compatibility (this breaks backward compatibility
for DB_ALL_NAMES, but that setting is unlikely to be set when
disabling it, and the unified behavior is worth the change).
This is closer to what go-ini does for parsing our config files [1],
and to the Postgres config file handling [2].
Fixes #245
[1]: …
> Handle booleans in config more consistently

- logs/stream/stream.go
- logs/stream/stream_test.go
This is in particular useful for GCP, where Pub/Sub does not guarantee
that associated lines will be received in order, e.g. when the DETAIL
line comes before the LOG line for log_min_duration_statement output,
causing parameters to be missed.
In passing, fix a bug in logline readiness handling that likely caused
some problems with Heroku logs, as we were considering logs to be "ready"
too often, due to a buggy comparison of the "logLine" loop variable
which we kept a long-lived pointer too (and then compared the next
iteration against that pointer, which would always succeed).
> Log streams: Support processing primary and secondary lines out of order

- logs/analyze.go
- logs/analyze_test.go
- state/logs.go
This avoids flagging the whole DETAIL log line as an unidentified line in
cases where the logdetail value is set by Postgres, e.g. because the
role that tried logging in does not exist (which is included in the
error message).
In passing, mark pg_hba.conf contents output by this log event as
OpsLogSecret.
> Log Insights: C22 Auth failed - detect additional DETAIL information

- runner/logs.go
- state/logs.go
You can see this minimized in https://go.dev/play/p/pZo9NWTiN2n versus https://go.dev/play/p/Z2ODTVDTgSR . The problem is that we copy the struct at the site of the defer. When we later replace the LogFiles slice, the copy captured by the defer is not updated, so when we run Cleanup, it cleans up only the empty slice in the captured copy. Adding a wrapper function means the struct is only copied when the deferred function is executed.
> Ensure temp files are cleaned up properly for RDS log processing

- Dockerfile
This is required to allow timezone parsing during log line handling.
> Docker image: Add tzdata package

- input/postgres/vacuum_progress.go
Currently we ensure that we have a v.relid, but that does not
guarantee that we match an entry in pg_class or in our
pg_stat_activity query.
If we have no table name to report (e.g., because of a manual VACUUM
running in a different database), omit the record from the vacuum
progress output.
Alternately, we could try to match manual vacuums in pg_stat_activity
in addition to autovacuums--is there a reason we're not doing that?
> Filter out vacuum records we cannot match to a table name

- input/postgres/relation_stats_ext.go
The citus_table_size function errors out if
citus.shard_replication_factor is greater than 1. Since checking this
is part of the extended stats collection, a shard_replication_factor
greater than 1 means schema collection will fail.
Check the citus.shard_replication_factor parameter before invoking the
function. Fall back to 0 since the field is nut nullable in our
snapshot.
> Check citus.shard_replication_factor before querying citus_table_size

- contrib/docker-entrypoint.sh
- input/postgres/backend_counts.go
- input/postgres/backends.go
- input/postgres/buffercache.go
- input/postgres/explain.go
- input/postgres/relation_bloat.go
- input/postgres/replication.go
- input/postgres/statements.go
- input/postgres/superuser.go
- input/postgres/vacuum_progress.go
- input/system/crunchy_bridge/logs.go
For now this is only utilized for the Crunchy Bridge log monitoring
integration, to allow use of the application user instead of the superuser.
> Add pganalyze.read_log_file helper to read files in the log_directory

- config/read.go
Due to Go's primitive os.Environ(), we do not correctly parse
environment variables whose values contain equal signs on Heroku. This
means the collector does not work with the new Heroku Postgres
Enhanced Certificates [1] or any other database URLs containing query
parameters.
Fix the parsing to correctly handle equal signs.
[1]: https://devcenter.heroku.com/articles/heroku-postgres-enhanced-certificates
> Fix Heroku environment parsing

- main.go
- util/logger.go
Add support for emitting logs as newline-delimited JSON with a bit of
structure matching the GCP stackdriver conventions [1]. I didn't use a library
like zerolog or zap because it seemed way overkill since there's already
a logging facade with util.logger, and we just need a way to dump output
to stderr.
[1]: https://cloud.google.com/logging/docs/structured-logging
Output looks like:
```json
{"severity":"INFO","message":"Running collector test with pganalyze-collector 0.43.0","time":"2022-04-19T12:31:05.100489-07:00"}
```
Future work could include:
- Using a more allocation efficient JSON encoder in place of Go's standard JSON
library. The format is simple enough that it's tempting to roll our own.
- Capturing more structured data like source-code location.
Fixes #261.
> logging: add option for structured JSON logs

- input/postgres/relation_stats.go
- input/postgres/schema.go
This helper must be installed in each database separately, but the
current warning does not say where the problem is.
Include the database name in the warning.
> Log database name in column-stats-helper-missing warning

- logs/parse.go
- runner/logs.go
We can't support log monitoring for Heroku Postgres' free tier, since
the log stream is not exported (intentionally, by Heroku), but previously
we would fail when running the test function, which may not be desirable
when multiple databases are mounted to the same collector application.
Instead emit a warning when the special log_line_prefix used by the
free tier is detected.
> Log test: Don't count Heroku Free Tier as hard failure (different prefix)

- input/system/azure/logs.go
- runner/logs.go
There are some differences in how Flexible Server sends data into the
Azure Event Hub as compared to Single Server, causing log lines to not
be processed. This attempts to parse lines for Flexible Server first,
and automatically falls back to the old special handling for
Single Server if that fails.
> Log processing: Add support for Azure DB for Postgres - Flexible Server

- util/logger.go
Otherwise, prefixed loggers won't use the JSON output.
> logging: keep UseJSON when creating prefixed loggers

- packages/repo/sync_deb.sh
There can be cosmic ray type errors from time to time causing bad
signatures - this ensures the signatures we made are actually valid, and
stops the build process if they are not.
> Package repo: Verify debian/ubuntu signatures after package updates

- input/system/google_cloudsql/logs.go
- logs/stream/stream.go
- logs/stream/stream_test.go
Whilst the GCP release notes mention that this is no longer a problem as of
Sept 2021, log events can still be split up into multiple messages if they
exceed a threshold around 1000-2000 lines, or ~100kb.
In order to fix message like this, re-enable the logic that was previously
turned off in commit 735d95cc4e6d4ab012a2a5a92bc282bd180c2fb1.
This can be reproduced by a query like this on a pgbench database:
SELECT aid FROM pgbench_accounts, pg_sleep(1)
UNION SELECT aid FROM pgbench_accounts --- repeat this line 100 times
ORDER BY 1 LIMIT 1
> Google Cloud SQL: Re-enable log stitching for messages

- input/system/heroku/logs.go
- logs/parse.go
- logs/parse_test.go
- runner/logs.go
Update the collector to support new Heroku log_line_prefix
Heroku recently updated the log_line_prefix on their new databases
[1]. Through regular maintenance, this new prefix will eventually come
to old databases as well. The new prefix is rejected by the collector
test and not parsed correctly by the log processing code.
Update the Heroku-specific code path to accept this new prefix as
well.
[1]: https://devcenter.heroku.com/changelog-items/2419
> Add support for new Heroku log_line_prefix

- input/postgres/statements.go
It's fairly common for customers to upgrade Postgres without realizing they need to upgrade pg_stat_statements as well. In that case, we show them an unhelpful error message:
```
Error collecting pg_stat_statements: pq: column "total_exec_time" does not exist
```
This PR updates the collector to instead use the correct `pg_stat_statements` columns based on the installed version of the extension, instead of the version we assume is installed based on the Postgres version.
If we know the extension is out of date we'll log a helpful message: (only during test runs)
```
pg_stat_statements extension outdated (1.6 installed, 1.8 available). To update run `ALTER EXTENSION pg_stat_statements UPDATE`
```
This PR also prevents errors when the extension is installed in a non-public schema, instead …
> Handle unexpected schema / version in pg_stat_statements

- input/postgres/settings.go
On some systems, notably Aurora Postgres 12.6, it appears possible to have
duplicate values in the pg_settings output, specifically as seen with the
"ssl_min_protocol_version" and "ssl_max_protocol_version" settings.
This is most likely a bug in the modified Postgres engine.
Since this causes other problems in the processing of the settings,
ensure that at most we get one result row per setting name.
> Fix rare bug with duplicate pg_settings values on Aurora Postgres

- config/read.go
Currently, we track which database logs belong to through
server.Config.Identifier, but that's not set for servers when running
on Heroku, which leads to all logs being sent to an arbitrary server.
Define server.Config.Identifier for Heroku servers like we do when
reading the config file.
This may have been broken in the refactoring in #240
> Fix Heroku log handling when consuming logs for multiple databases

- input/system/heroku/logs.go
On Heroku, Postgres log messages that include newlines don't render a
space between the standard line header and the (empty) output. Note the
log message:
```
2022-07-02T00:54:04.000000+00:00 app[postgres.1167776]: [YELLOW] [13-1]  sql_error_code = 00000 time_ms = "2022-07-02 00:54:04.414 UTC" pid="1299178" proc_start_time="2022-07-02 00:51:59 UTC" session_id="62bf96af.13d2ea" vtid="4/9659035" tid="0" log_line="6" database="d4anv5h51mo8t8" connection_source="44.197.170.157(34910)" user="uablvp9bo3lp3h" application_name="psql" NOTICE:  hello
2022-07-02T00:54:04.000000+00:00 app[postgres.1167776]: [YELLOW] [13-2]
2022-07-02T00:54:04.000000+00:00 app[postgres.1167776]: [YELLOW] [13-3]
2022-07-02T00:54:04.000000+00:00 app[postgres.1167776]: [YELLOW] [13-4] 	world
```
and the hexdump it …
> Fix Heroku blank log line parsing

- input/system/system.go
This stopped working when we introduced the dedicated Crunchy Bridge
system type. Since container apps run directly on the database server,
we can use the same mechanism to get system metrics as we do for self
hosted servers.
> Crunchy Bridge: Fix collection of system metrics

- logs/parse.go
- logs/parse_test.go
This covers a typical log_line_prefix setting used by the Ubuntu Postgres
packages, and adds a variant with hostname, that was requested.
> Add additional log_line_prefix "%m [%p] %q%u@%d " + variant with %h

- input/postgres/relations.go
- input/postgres/types.go
See 63be3a0d7b2b71a59fe1287b849d3159eb00383f -- a similar problem can
occur with constraintdefs, if those defs are foreign key table references.
> Stop pretty-printing constraintdefs on collection

- main.go
- state/state.go
This allows testing a subset of the full configuration file by specifying
the section heading that should be tested.
For example this may be used as part of adding a new server configuration,
to avoid waiting for test snapshots for unrelated servers.
> Add --test-section parameter to set a specific config section to test

- README.md
- config/config.go
- config/read.go
- input/postgres/log_pg_read_file.go
- input/system/heroku/http_handler.go
- input/system/system.go
- main.go
- runner/emit_test_lines.go
- runner/logs.go
This is an alternate approach to collecting log data that relies on
built-in Postgres functions to read log files and return the log data to
the collector over the Postgres connection.
Note that this requires superuser (either directly or through a helper)
and thus does not work on managed database providers, with the exception
of Crunchy Bridge, for which this is already the mechanism to fetch logs.
Additionally, this carries higher overhead than directly tailing log
files, or using syslog, and thus should only be used when necessary.
You can enable this by setting the "db_log_pg_read_file" /
"LOG_PG_READ_FILE" setting to "1" or "true", and ensuring that the
"pganalyze.read_log_file" helper exists (or by connecting as a superuser).
> Allow using "pg_read_file" for self-managed servers to read log files

- config/config.go
- config/identify_system.go
- config/read.go
- input/system/google_cloudsql/logs.go
- logs/analyze.go
- logs/analyze_test.go
This adds two new configuration options for configuring a particular AlloyDB instance:
* gcp_alloydb_cluster_id / GCP_ALLOYDB_CLUSTER_ID
* gcp_alloydb_instance_id / GCP_ALLOYDB_INSTANCE_ID
Additionally, the gcp_project_id / GCP_PROJECT_ID has to be set as well.
Instead of going through the regular Cloud SQL log parsing, this utilizes
special logic that removes the source filename and line, which are
added by AlloyDB but not by standard Postgres.
In passing, accomodate special autovacuum log syntax used by AlloyDB.
Note there may be other log events with similar customizations we don't handle yet.
Fixes #272
> Add support for Google AlloyDB for PostgreSQL

- Makefile
> Makefile: Ignore errors when determining DOCKER_RELEASE_TAG

- .github/workflows/ci.yml
- .github/workflows/release.yml
We sometimes hit GitHub rate limits in the setup-protoc action, which
causes the build to fail [1]. The action documentation recommends
passing your workflow's GITHUB_TOKEN to make an authenticated request
for protobuf version lookups: even though the API endpoint is public,
unauthenticated requests have lower IP-based rate limits.
Pass the token to the action, but also fork the action into our own
repo and remove unnecessary permissions from the token as extra
defensive measures.
I've reviewed the existing action code and the token is only used for
the GitHub API request to fetch protobuf releases.
[1]: https://github.com/pganalyze/collector/runs/7732070234?check_suite_focus=true#step:3:8
> Pass GitHub token to setup-protoc action

- runner/logs.go
In fd65610fd60b0aaa2b2784ba23bb7f7e09c7f71e, we added a hint to
instruct users to check the instance role when hitting RDS credential
erros in log download. This works, but only in the live code path,
because the test code logs the download error from a different entry
point.
To work around this, add the same warning to the test code path.
Alternately, we could push the logging down into the download method
itself (in code that both code paths end up calling), but that breaks
up the logging success/failure cases in a weird way, especially for
the test path. Or we could build an error that includes the hint,
though there's less flexibility in formatting (the hint cannot be its
own line) if we do that. Finally, we could also use an error type that
includes separate message and hint fields, …
> Show RDS instance role hint when running collector test

- input/system/rds/logs.go
The way the existing code was written was creating a new local
variable called "err" that shadowed the top-level "err" variable. This
then lead to errors being silenced since the ErrorCleanup code path
was referencing the top-level "err" which was set to nil even in error
conditions.
The practical consequence of this was that if an IAM policy was in use
that permitted DescribeDBLogFiles but not DownloadDBLogFilePortion, the
log data would be empty, without any errors shown in the logs. This
can occur when someone grants the RDS Read Only predefined IAM policy
instead of a custom policy with our recommended permissions.
> RDS logs: Don't silence errors by accident due to variable shadowing

- main.go
- util/logger.go
This re-uses an existing code path for Quiet in the logger (not used
before this change), and adds warnings to be hidden as well when quiet
is active.
See #310 for related discussion.
> Add "-q" / "--quiet" flag to hide all log messages except errors

- .github/workflows/release.yml
This was added in 8a5387cefb1287d0ed81a3b4a40dab811b2f6e45 to avoid the protoc
action using a more privileged token to do GH downloads, but broke the release
step by accident. For the release action only apply the permission limits to
the build step. For the CI action we keep the limits for the whole action.
> GH actions: Only apply permissions restrictions to build job

- input/system/rds/logs.go
The RDS log download looks at any log file that was modified in the last
two minutes, to make sure to not miss any data when a new log files is
started. Each log file is processed separately with its own tempfile
that stores the downloaded log data. However the amount of data written
to the files was kept in a single variable that was not reset between
files causing errors like the following:
Error reading 65817 bytes from tempfile: unexpected EOF
Fix by moving the variable into the loop that handles each file. This is a
long-standing error that was hidden before due to the bug now fixed in
d31e3af77b087338d02b2e7e5eeb8fc4c0ba912e.
> RDS log download: Fix edge case that caused errors with multiple files

- contrib/docker-entrypoint.sh
This allows easier configuration of multiple servers to be monitored by
the same Docker container. Previously this required use of a volume
mount, which can be harder to make work successfully.
CONFIG_CONTENTS needs to match the regular configuration file format that
uses separate sections for each server.
This can be combined with environment-variable style configuration for
settings that apply to all servers (e.g. PGA_API_KEY) but all
server-specific configuration should only be passed in through the
CONFIG_CONTENTS variable.
> Docker: Allow setting CONFIG_CONTENTS to pass ini-style configuration

- main.go
- output/compact.go
- output/full.go
- state/state.go
The new flag `--benchmark` allows you to run collector without submitting stats. With this, you can run collector without connecting to pganalyze, which will be helpful for benchmarking as you can skip the setup, as well as ignore the overhead of that part.
Difference between other flags:
* `test`: this only runs once, and also submit the stats to the server (setup is needed)
* `dry-run`: this also only runs once, and print the JSON data to stdout (which is not needed for benchmarking)
> Introduce benchmark flag to support running collector without submitting stats

- input/postgres/statements.go
- integration_test/Dockerfile.test-pg14
- integration_test/Dockerfile.test-pg15
- integration_test/Makefile
- integration_test/pg14.expected
- integration_test/pg15.expected
- state/postgres_version.go
There was a bug in our version check mechanism that caused the minor version "1.10" to be treated as smaller than "1.8", effectively causing us to look for the wrong fields.
Fix the relevant version comparisons to use integer instead of floats, and in passing cleanup some old references to Postgres version numbers as compared to pg_stat_statements version numbers.
In passing add the version strings for Postgres 14 and 15, in case we add version-specific checks in the future.
> Statements: Fix Postgres 15 compatibility due to version check bug

- integration_test/Dockerfile.test-citus
- integration_test/Makefile
- integration_test/citus-pgbench-ddl.sql
- integration_test/citus.expected
- integration_test/docker-entrypoint-initdb.d/postgres-pgss.sh
This adds a very basic run-through of pganalyze on a Citus
workload. It uses the latest Citus image and modifies the default
pgbench schema we use in stock Postgres tests to use Citus distributed
tables. This ensures monitoring features like calculating distributed
table sizes on Citus are properly exercised.
> Add Citus integration smoke test

- input/postgres/relation_stats.go
- input/postgres/relation_stats_ext.go
Currently, when monitoring Citus databases, we collect distributed
table sizes with Citus' `citus_table_size` helper function, but we
ignore indexes on these distributed tables.
Add a similar calculation for index sizes. While there is a similar
`citus_relation_size` that is documented to work for distributed
indexes, it does not [1]. Instead, we use `run_command_on_shards` to
get this information from the underlying catalog objects and stats
directly.
[1]: I filed https://github.com/citusdata/citus/issues/6496 which
seems to be getting some attention, so maybe there is hope for a
better fix
> Collect Citus distributed index sizes

- config/config.go
- config/read.go
- input/system/system.go
Now we try to read the value of `always_collect_system_data` in the config file, as well as the original `PGA_ALWAYS_COLLECT_SYSTEM_DATA` environment variable.
This is useful for ~~non-container setups which connect to remote servers~~ package-based setups which monitor the local server by a non-local IP.
> Add `always_collect_system_data` config option

- config/read.go
solving #344 
> Hello,
> 
> Thank you for your work.
> 
> I have one of our add-on that add a ENV on our running collector; this env is named HEROKU_METRICS_URL. The problem is that the collector handle it as a PG URL and try to connect to it. There is no immediate problem with this kind of behavior, but there are two glitches.
> 
> The collector adds a DB named HEROKU_METRICS on PGAnalyze website
> when I run collector --test there is some log saying that he can't connect to this DB, as it's an HTTPS URI: (https://app.metrics.heroku.com/[...REDACTED...])
> There are 2 solutions. Add a denylist (or allowlist) OR detect that the URL isn't a pg schema.
> ```
> `postgres(?:ql)?.*\`gm
> ```
> Ignore non-postgres URIs in environment

- config/read.go
We write these out to temporary files since we need to hand these to
pq via file names. We check for errors writing out the root cert, but
not the cert or the key.
Add the error checks.
Found while adding tests for #358.
> Do not ignore errors when writing out SSL config to temp files

- input/postgres/backend_counts.go
- input/postgres/backends.go
- input/postgres/buffercache.go
- input/postgres/databases.go
- input/postgres/extensions.go
- input/postgres/functions.go
- input/postgres/log_pg_read_file.go
- input/postgres/relation_bloat.go
- input/postgres/relation_stats.go
- input/postgres/relation_stats_ext.go
- input/postgres/relations.go
- input/postgres/replication.go
- input/postgres/roles.go
- input/postgres/sequences.go
- input/postgres/settings.go
- input/postgres/statements.go
- input/postgres/types.go
- input/postgres/vacuum_progress.go
- input/postgres/vacuum_stats.go
When we're reading rows data, we usually check if the scan was good in each row, but we don't check the error after iterating over rows. This is not following the suggested usage (http://go-database-sql.org/retrieving.html), and unfortunately ignoring errors like query timeout.
This is especially problematic when the subsequent code is using the result of these rows, as if it timed out in the middle, it will have incomplete rows data (e.g. `GetRelations()` in `input/postgres/relations.go`, where it gets the table list first, then use that table list with the other query like columns info).
With this PR, introducing such check for every place that we're doing `rows.Next()`. I also double checked if we're doing `defer rows.Close()` properly (fixed one place). Hopefully this will improve the
> Check errors with rows after iterating

- config/read.go
- config/read_test.go
Currently, we assume that Aiven hostnames follow the pattern
{service-id-part1}-{service-id-part2}-{project-id}.aivencloud.com
This is the case for default service names, but a service name does
not need to be dash-separated.
Update our detection logic to account for arbitrary project names that
follow Aiven's documented pattern
<SERVICE_NAME>-<PROJECT_NAME>.aivencloud.com
Assume that project names do not contain dashes (setting
aiven_project_id and aiven_service_id manually is still an option if
that's not the case).
> Improve Aiven Service ID and Project ID detection from hostname

- main.go
In 9e76ee117019867bd3d5586f1db401fa8fff3b8c, we relaxed collector
restrictions on log line processing. Previously, any unsupported
settings would disable log processing altogether. After that change,
in some cases, unsupported log lines would be ignored and other lines
could still be processed. However, the commit did not add similar
warnings for the new cases. This could be confusing, since it can lead
to log lines silently being ignored.
Add a warning for the cases when log lines are dropped. Only emit the
warning on startup (including during a test), since this is an
expected situation and impact is limited.
> Warn if some log lines will be ignored

- Dockerfile
Currently, attempting to build the main Dockerfile on my machine fails
on step 17:
Step 17/22 : COPY --from=base --chown=pganalyze:pganalyze /home/pganalyze/docker-entrypoint.sh /home/pganalyze/collector /home/pganalyze
When using COPY with more than one source file, the destination must be a directory and end with a /
I'm using the latest Docker (version 20.10.22, build 3a2c30b).
The documentation [1] also claims
If multiple <src> resources are specified, either directly or due
to the use of a wildcard, then <dest> must be a directory, and it
must end with a slash /.
so it's not clear how this is working in other situations.
Adding a trailing slash to this COPY's destination (i.e., change it to
"/home/pganalyze/") makes the build succeed here (and should not
affect the build otherwise). …
> Add missing slash to Dockerfile COPY command

- input/system/rds/logs.go
During log parsing and analysis we set the byte offsets for each log line in respect to a temporary file on disk. In the current implementation we don't use this temporary file during log analysis (but rather an in-memory buffer of just the data that needs to be analyzed), but we do utilize that file when encrypting and uploading the data, and all log line offsets are assumed to be in respect to the file on disk.
Whilst we may want to rework this mechanism to not upload data that was not analyzed, the current logic will incorrectly set the offsets in situations where the temporary log file size exceeds 10 MB (the limit of the maximum data we process per log snapshot on RDS). For now, fix the immediate bug here by passing through the correct start offset.
> RDS log download: Ensure we pass through read start offset to log parsing

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Dockerfile
- config/config.go
- go.mod
- integration_test/Dockerfile.test-citus
- integration_test/Dockerfile.test-guided-setup
- integration_test/Dockerfile.test-pg10
- integration_test/Dockerfile.test-pg11
- integration_test/Dockerfile.test-pg12
- integration_test/Dockerfile.test-pg13
- integration_test/Dockerfile.test-pg14
- integration_test/Dockerfile.test-pg15
- integration_test/Dockerfile.test-pg96
- integration_test/Dockerfile.test-reload
- packages/src/Dockerfile.build.deb-systemd
- packages/src/Dockerfile.build.rpm-systemd
Go 1.17 has been EOL for six months. Reviewing the changelog [1],
there do not appear to be any breaking changes.
[1]: https://tip.golang.org/doc/go1.18 and https://tip.golang.org/doc/go1.19
> Upgrade to Go 1.19

- state/postgres_relations.go
- state/postgres_relations_test.go
A fix for the bug introduced in https://github.com/pganalyze/collector/pull/350.
Currently, when the zero of frozen XID is provided, `FullFrozenXID` will return the first XID of the current epoch. This is a wrong behavior and we should return 0 as frozen XID instead as it has the different meaning.
> Return full frozen XID as zero if the original one is zero

- config/config.go
- config/read.go
- go.sum
- input/postgres/establish_connection.go
- setup/steps/ensure_monitoring_user_password.go
- vendor/github.com/aws/aws-sdk-go/service/rds/rdsutils/builder.go
- vendor/github.com/aws/aws-sdk-go/service/rds/rdsutils/connect.go
- vendor/github.com/aws/aws-sdk-go/service/rds/rdsutils/doc.go
- vendor/modules.txt
This adds a new configuration setting, db_use_iam_auth / DB_USE_IAM_AUTH that, if enabled, causes the collector to fetch a short-lived token for logging into the database instance from the AWS API, instead of using a hardcoded password in the collector configuration file.
In order to use this setting IAM authentication needs to be enabled on the database instance / cluster, and the pganalyze IAM policy needs to be extended to cover the "rds-db:connect" privilege for the pganalyze user:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.IAMPolicy.html
Note that for now the collector will fetch a new token for each connection it makes (at least one new connection every 10 seconds), which may cause additional AWS API utilization when monitoring a lot of instances. …
> Support IAM token authentication for Amazon RDS and Amazon Aurora

- input/system/rds/logs.go
- util/awsutil/rds.go
Previously the log download for RDS would issue a DescribeDBInstances call for confirming whether the instance ID is indeed valid.
Whilst this was made less problematic by addition of a cache in f2ab72f45bd, it missed the fact that we don't actually need to do this lookup at all in the case of log downloads for Amazon RDS instances.
Instead, we can just rely on the later DescribeDBLogFiles API call to complain if an instance ID does not exist. Thus, this change removes that API call completely for log downloads when the instance ID is specified.
In the case of Aurora we do need the API call to DescribeDBClusters to find the specific instance ID, e.g. that of the current writer. In terms of caching we can't cache the cluster ID => instance ID mapping for risk of missing a failover event …
> AWS: Avoid DescribeDBInstances calls for log downloads for RDS instances

- logs/parse.go
- logs/parse_test.go
Some of the timezone abbreviations don't use a name like "EST" but instead use the offset from UTC in hours. It seems that Golang's time.LoadLocation does not support this correctly, and thus parsing fails.
To fix this, add handling for parsing numeric offsets directly without going through the timezone database.
> Log parsing: Add support for timezones specified by number, such as "-03"

- packages/test/Makefile
This was broken seemingly by accident, without any upstream updates as of yet. Since we are also testing rhel9 this seems like a "nice to have" and we can re-enable the test once the upstream issue is fixed.
See https://github.com/rocky-linux/sig-cloud-instance-images/issues/39
> Package test: Remove rockylinux9 from defaults due to missing /sbin/init

- CHANGELOG.md
- CONTRIBUTING.md
- contrib/helm/pganalyze-collector/Chart.yaml
- packages/Makefile
- util/version.go
Cutting a new release for 0.48.0. Bumping the minor version as it includes Go version update + somewhat important bugfix.
Also adding a memo for how to create a new release inside of CONTRIBUTING.md file.
> Release 0.48.0

- input/postgres/relations.go
Previously the constraints query included foreign tables, unlike the earlier query for gathering relation info that excluded them. This then causes a bogus empty table to show up in the snapshot, due to Go initializing an empty struct when looking up an OID that does not exist.
Fix by aligning the constraints query with the other queries, and ignoring the same kind of tables.
> Relation stats: Correctly filter out special tables for constraints query

- state/postgres_relations.go
- state/postgres_relations_test.go
We currently set `currentXactId` to 0 when it's in recovery mode (aka replicas). This PR fixes the issue of the `FullFrozenXID` becomes negative when 0 is passed as `currentXactId`. Instead, `FullFrozenXID` will become zero.
This will introduce a slight inconsistency for what we return as the data. Let's think about the following case:
* current xact id is epoch 1 + 300, multixact id is 30
* database/table
* frozen_xid 100, age 200
* min_mxid 10, age 20
For non-replica, it'll return:
* current xact id: (1 << 32) + 300, multixact id: 30
* database
* frozen_xid 100, age 200
* min_mxid 10, age 20
* table
* frozen_xid (1 << 32) + 100, age 200
* min_mxid 10, age 20
For replica, with this PR, it'll return:
* current xact id: 0, multixact id: 0
* database
* frozen_xid 100, age 200
* min_mxid 10, …
> Return zero as FullFrozenXID for replicas

- logs/parse.go
Sometimes log lines can be excessively long, but the log_line_prefix is almost always a tiny portion of such log lines. Since we are currently doing Regexp-based parsing for log lines (before analysis), it can be expensive to pass such large log lines in full to the Go regexp engine.
Instead, only pass the first 1000 characters to the Regexp engine when reading out the log_line_prefix fields. In a real world test case this improves the parsing performance for a 2.1GB log file from 17 minutes to 14 minutes (tested with "time pganalyze-collector --analyze-logfile"), and its hard to imagine a case where the prefix is longer than 1000 characters.
> Log parsing: Only consider first 1000 characters for log_line_prefix

- input/postgres/log_pg_read_file.go
- input/system/rds/logs.go
- logs/stream/stream.go
- logs/stream/stream_test.go
- runner/logs.go
- state/logs.go
- util/tmp_file.go
We've previously introduced a limit of 10 MB of log data per file tracked in a log snapshot, to avoid causing log analysis to time out in cases of very large log events, or other issues that caused a lot of data to be written since the last log marker.
However, the prior logic was still keeping the full original log data around *and* unnecessarily encrypted and submitted that data, even though it was not actually usable. Additionally, the prior logic was hard to reason about, and had subtle bugs, such as the one fixed in 90db3291ec.
Instead, in cases of the downloaded log data exceeding 10 MB, write out a new temporary file that contains just that data. In addition, add a warning in the collector logs to highlight when this happens, so that a user may take action (e.g. reduce occurrence …
> Amazon RDS/Aurora: Improve handling of excessively large log file portions

- input/system/azure/logs.go
- input/system/azure/logs_test.go
The code previously did not work correctly since the log_line_prefix was not present on the DETAIL lines (which are included on the main log line on Azure). This subsequently caused issues with log-based EXPLAIN not having DETAIL lines available.
Fix by reworking how log lines get transformed for Azure, and adding unit tests for the transformation based on examples from running "pgbench -M extended".
> Fix Azure Single and Flexible Server log line parsing for DETAIL lines

- .github/workflows/release.yml
GitHub actions automatically updated the "ubuntu-latest" release to 22.04, which uses a fairly new glibc that breaks use of the release binary on older operating systems.
Since we're not in a rush to build on 22.04 for the release task, pin to 20.04 to ensure an older minimum required glibc version.
> Release task: Use Ubuntu 20.04 release to release binary with older glibc

- README.md
Whilst we're planning to overhaul this section of the README soon, there is a very common problem that one can run into if you forget to grant the pganalyze user usage on the schema for the restricted monitoring user - fix that since its straightforward to do.
This matches documentation pages such as https://pganalyze.com/docs/install/amazon_rds/02_create_monitoring_user
> README: Add missing GRANT USAGE for helper functions

- input/postgres/relation_stats.go
- input/postgres/relations.go
- output/transform/postgres_relations.go
- runner/diff.go
- state/postgres_relation_stats.go
```
Relation queries: Correctly handle later queries encountering a lock
The existing coding assumed that we can rely on the fact that a relation
is exclusively locked to stay the same across each query that works with
relation data to get columns, indexes, constraints, etc.
But that is not true (locks can change between the queries) and that
causes a race condition where the first query does not see a relation
being locked, but later queries do. This then causes downstream problems
since only part of the information was sent, and e.g. an index might
show in one snapshot, and then disappear in the next, if locking
conditions are unlucky.
To fix, return which exclusive locks each relation query encountered, and
take that to consider the relation having been exclusively locked for the
whole …
```
> Avoid partial data and bogus statistics when locks are encountered in parts of the snapshot

- config/config.go
- config/read.go
- input/postgres/relation_stats.go
- input/postgres/relation_stats_ext.go
- input/postgres/schema.go
For certain Citus deployments, running the relation or index size functions can fail or time out due to a very high number of distributed tables.
Add the new option "disable_citus_schema_stats" / "DISABLE_CITUS_SCHEMA_STATS" to turn off the collection of these statistics. When using this option its recommended to instead monitor the workers directly for table and index sizes.
> Add option to turn off collection of Citus schema statistics

- output/transform/postgres_relations.go
In https://github.com/pganalyze/collector/pull/391, we stopped sending out the data like `RelationInformations` and `RelationStatistics` when the relation is exclusively locked.
However, this caused the issue on the pganalyze app side, because we're still sending out `RelationReferences` yet we weren't able to find the corresponding `RelationInformations` with it. When storing the `RelationReferences`  data, we use the information of `RelationInformations`, especially `RelationType` data.
With this change, revert stop sending out the `RelationInformations` data. This should be the only info that we need but dropped (we are okay not having `RelationStatistics` or other things), and we also shouldn't have the "bad data" with `RelationInformations` because we can still get this basic …
> Send out exclusively locked relation info

- input/full.go
Previously this was a hard error, which failed the snapshot - this is not desirable because hard errors mean the snapshot state does not get persisted. In practice this meant that the error would very likely occur again on the next full snapshot run, in the typical case of a permission problem. This meant that full snapshots kept failing, which indirectly led to a memory leak because the UnidentifiedStatementStats list would keep growing (as the query runner was working just fine, once a minute).
To fix, emit only a warning instead, and process the rest of the snapshot as usual, thus persisting the state and not calling the reset function again until the next scheduled interval.
Fixes #398
---
Separately, as a defense against this class of bugs causing memory leaks, we should review in a …
> Query stats reset: Make pg_stat_statements_reset() failure a soft error

- runner/logs.go
Contrary to the existing hint, this can also occur when one simply forgets to assign a managed identity to the VM. Its easier for us to explain this on a web page, so link to the troubleshooting page instead.
Note that I have some pending docs improvements (https://github.com/pganalyze/pganalyze-docs/pull/145/commits/a4275f413b6ca5ec0a9fef104bc40dbaa0f57b6b) that carry over the existing hint messaging to the docs.
> Azure: Add troubleshooting link for Azure AD provider error

- scheduler/scheduler.go
#384 added a deadline / timeout for each snapshot, but this is leading to data loss for a customer with a collector process that monitors 20+ servers. When monitoring so many servers it's possible that network requests, for example, could cause activity snapshots to not reliably finish within 10 seconds. A future refactor may move snapshot uploads to a separate deadline, but this PR should mitigate the issue for now.
> Extend the deadline for activity snapshots

- scheduler/scheduler.go
This makes it easier for a future reader to understand, since it matches the if condition with the override we're setting.
In practice this doesn't actually matter with the current scheduler config since we either have 10 seconds or 1 minute apart, and thus the 10 seconds interval would already have matched as a very short deadline.
See https://github.com/pganalyze/collector/pull/406#discussion_r1156552159
> Scheduler: Use 19 seconds to check for very short deadlines

- packages/Makefile
The syntax added in the previous commit does not work within Makefiles, only in bash. Instead use "?=" which is the correct way to allow overriding Makefile variables from the environment.
In passing, default the GIT_VERSION to be the version prefixed by "v", to have one less variable to change when releasing a new version.
> packages Makefile: Fix variable default logic to not assume bash

- .github/workflows/release.yml
This accidentally led to the package upload to the release entry not working as intended, since the package names use the raw version number without the "v" prefix used in the git tag.
> Release task: Correctly use version without "v" prefix

- contrib/install.sh
In passing fix unnecessary output of ${distribution} when failing, which will always be empty in the else branch of the script - we already output the /etc/os-release file which is what we'd need for debugging.
> Collector install script: Add Amazon Linux 2023, refresh other versions

- packages/src/rpm-systemd/post.sh
- packages/src/rpm-systemd/preun.sh
This was an oversight in the packaging logic, since we utilize fpm's "--deb-systemd-auto-start" setting for the Debian-based packages, but we don't have the equivalent for the RPM packages.
Fix by adding an explicit "systemctl enable" on installation, and a corresponding "systemctl disable" on removal, matching what was already done for the Debian packages.
> RPM packages: Ensure collector gets started after reboot

- main.go
- scheduler/scheduler.go
It's fairly common for users to make a config change and verify it with `--test`, but forget to include `--reload` so the background collector continues running with the old configuration. ~~This PR attempts to reduce our support burden by automatically reloading the configuration every hour.~~
Another option might be to always reload the configuration after a successful test run, removing the `--reload` flag.
> Reload collector config after successful test run

- logs/analyze.go
- logs/analyze_test.go
- logs/querysample/querysample.go
- logs/util/parse.go
This can happen because of stitching; we can't just look for them at
the end.
> Look for truncation messages in the middle of log lines

- README.md
The pganalyze collector is maintained by pganalyze as a team, and so it doesn't make sense to reflect individual authorship in the README (a list which by now was also clearly outdated).
In passing, adjust the copyright to match the style we use in other repositories.
> README: Don't list individual authors, adjust copyright to match common style

- main.go
Due to a coding oversight that dates a while back, the exit code is only set when doing test+reload, but not when doing just test.
Whilst a recent change has flipped the default of test to also execute reload automatically, it doesn't hurt to return a failue exit code (1) in case of failure when "--no-reload" is specified.
> Collector test: Always return correct exit code, even with --no-reload

- output/transform/postgres.go
Bugfix. With xmin horizon stats, ReplicationSlot was used for XminHorizonReplicationSlotCatalog, wrongly. This PR fixes it.
> Fix bug where xmin horizon ReplicationSlot was wrongly set to ReplicationSlotCatalog

- go.mod
- go.sum
- vendor/github.com/satori/go.uuid/.travis.yml
- vendor/github.com/satori/go.uuid/LICENSE
- vendor/github.com/satori/go.uuid/README.md
- vendor/github.com/satori/go.uuid/codec.go
- vendor/github.com/satori/go.uuid/generator.go
- vendor/github.com/satori/go.uuid/sql.go
- vendor/github.com/satori/go.uuid/uuid.go
- vendor/modules.txt
Fixes CVE-2021-3538 which may have led to random UUIDs having less randomness than intended. This is not a direct security issue since all generated UUIDs are still separated by server when processed, but it seems good to resolve in any case to make dependency scanners happy.
Per report from Jonathan Yu. Fixes #428.
> Update github.com/satori/go.uuid to 1.2.0

- logs/analyze.go
- logs/analyze_test.go
Whilst we have supported other syntax that was introduced in Postgres 14, we missed the fact that new index vacuum details were added for each index of a table. This caused events to not be detected correctly.
See https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=5aed6a1fc214913de9ac69c1717dc64a2483e16d
> autovacuum logs: Match index vacuum information in Postgres 14+

- logs/analyze.go
- logs/analyze_test.go
Previously we only considered the direct cancellation context output by autovacuum.c (used sometimes), but autovacuum can also have additional information in which phase autovacuum was cancelled via a special error context helper, which supersedes the other context.
Support parsing both cases, so we can link the cancellation event to the relation reliably. Additionally, fix an accidental omission of the "automatic vacuum of table" case (we only considered analyze), output by autovacuum.c.
> Log analysis: Add more cases for "canceling autovacuum task" context line

- logs/analyze.go
- logs/analyze_test.go
Due to the way we associate log lines to relation references, we need to have a fully qualified name that has both a schema and relation name.
Unfortunately Postgres currently never outputs a schema name for the "skipping vacuum" and "skipping analyze" events, only the table name itself - which caused us to not associate the line to a relation.
To allow filtering on the application side through special logic that can look at tables in all schemas matching the name, remember the relation name in the unstructured details field of the log line, and stop storing it in the RelationName field (which was never sent to the server anyways).
> Log analysis: Remember unqualified name for "skipping vacuum" events

- packages/repo/Dockerfile.repo-rpm
- packages/repo/sync_rpm.sh
In passing, add the "-v" switch to the "rpm --checksig" command so we can easily see which signature was used.
---
Before:
```
/rpm/systemd/pganalyze-collector-0.50.1-1.x86_64.rpm:
Header V4 RSA/SHA1 Signature, key ID a2b5f2f9: OK
Header SHA1 digest: OK (7461f9f24bcd3cb5d52bac85de3541a0b5f48f2a)
V4 RSA/SHA1 Signature, key ID a2b5f2f9: OK
MD5 digest: OK (b7b80dd6da1fae32d76e86d6673cfc00)
/rpm/systemd/pganalyze-collector-0.50.1-1.aarch64.rpm:
Header V4 RSA/SHA1 Signature, key ID a2b5f2f9: OK
Header SHA1 digest: OK (455543595f47e9402383c85f1a8540044d6b5e5c)
V4 RSA/SHA1 Signature, key ID a2b5f2f9: OK
MD5 digest: OK (4e57b10b5de21dcec17ca459117ad1b7)
```
After:
```
/rpm/systemd/pganalyze-collector-0.50.1-1.x86_64.rpm:
Header V4 RSA/SHA256 Signature, key ID a2b5f2f9: OK
Header SHA1 digest: OK …
```
> RPM Packages: Switch to SHA256 signatures to fix RHEL9 install errors

- input/full.go
- input/system/azure/logs.go
- input/system/google_cloudsql/logs.go
- input/system/heroku/logs.go
- input/system/selfhosted/logs.go
- logs/parse.go
- logs/parse_test.go
- logs/replace_test.go
- main.go
- state/state.go
- state/util.go
Right now, we infer the log timezone by parsing this out of log lines.
This works in theory, but in practice Go's time.LoadLocation does not
support many timezone abbreviations (and abbreviations can be
ambiguous anyway).
Since we already collect Postgres settings, and these specify the log
timezone in a non-abbreviated form, we can use these. These correspond
to the full name in the IANA Time Zone database, as time.LoadLocation
expects. Sync this on every full snapshot just in case the timezone is
updated.
The current implementation stores this state on the Server, protected
by a new mutex. Since this needs to be written by the full snapshot
and read during log parsing, none of the existing mutexes or state
seemed appropriate. I admit this is not a great solution and I'm open
to other …
> Use log_timezone setting to determine log timezone if possible

- logs/analyze.go
- logs/analyze_test.go
This adds support for the changes done in the following upstream commits:
* Simplify lazy_scan_heap's handling of scanned pages https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=44fa84881fff4529d68e2437a58ad2c906af5805
* Add VACUUM instrumentation for scanned pages, relfrozenxid. https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=872770fd6ccf12596b9e26234df9a37cae083af2
> Autovacuum log parsing: Add support for updated format in Postgres 15+

- Makefile
This avoids automatically regenerating compiled protoc files with a
new version whenever protoc-gen-go has a release. The current behavior
makes it easy to include changes from a new tool version alongside
with other unrelated changes, which could make it harder to track
down problems.
Pin protoc-gen-go like we pin our other dependencies. We can update it
manually as necessary.
> Pin protoc-gen-go to specific version

- .github/workflows/test-packages.yml
- contrib/install.sh
- packages/repo/sync_deb.sh
- packages/src/Dockerfile.build.deb-systemd
- packages/test/Makefile
This also stops building packages for Buster (10), which has reached EOL.
Fixes #437
---
Separately this also drops Ubuntu 16.04 and 18.04 which are both EOL as well, and the Bullseye glibc is too new for them to be supported.
> Debian: Bump minimum required version to Bullseye (11), add Bookworm (12)

- input/postgres/replication.go
Previously we skipped processing of replication statistics for Aurora, since the regular built-in Postgres replication functions error out in many cases. However, this also meant that all Aurora instances were always detected as primaries, regardless of whether they were a writer or a reader, which led to confusing in-app experiences.
Fix by adding Aurora-specific logic in the replication stats collection.
This also adds support for ignoring Aurora readers using the "skip_if_replica" collector configuration option. This can be used when specifying Aurora instances individually as servers, but only intending to monitor the writer. Note that for such situations we do generally recommend specifying the cluster write endpoint instead, but there is no downside to support this alternate way of …
> AWS Aurora: Correctly detect Aurora reader instances as replicas

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Dockerfile
- go.mod
- integration_test/Dockerfile.test-citus
- integration_test/Dockerfile.test-guided-setup
- integration_test/Dockerfile.test-pg10
- integration_test/Dockerfile.test-pg11
- integration_test/Dockerfile.test-pg12
- integration_test/Dockerfile.test-pg13
- integration_test/Dockerfile.test-pg14
- integration_test/Dockerfile.test-pg15
- integration_test/Dockerfile.test-reload
- packages/src/Dockerfile.build.deb-systemd
- packages/src/Dockerfile.build.rpm-systemd
```
Update Go version in use for packages and tests to 1.21
Additionally, this bumps up the minimum Go version to 1.20, and uses
that on Heroku, as Heroku's Go buildpack does not yet support 1.21.
```
```
Dockerfile: Update alpine base image from 3.15 to 3.18
```
```
Update Go download location from "golang.org" to "go.dev" domain
This has been changed upstream, and it seems reasonable to match.
```
> Update Go version to 1.21, update Dockerfile alpine base image to 3.18

- CONTRIBUTING.md
This is pretty basic. But I didn't see that `protobub/` was a submodule. On a basic git clone, folder was empty leading to:
```
~/code/collector main ❯ make build 
mkdir -p /Users/benoit.tigeot/code/collector/bin
GOBIN=/Users/benoit.tigeot/code/collector/bin go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.31.0
protoc --go_out=. --go_opt=module=github.com/pganalyze/collector -I protobuf
Missing input file.
make: *** [output/pganalyze_collector/snapshot.pb.go] Error 1
```
> Do not forget submodules when fetching the project

- input/full.go
- input/system/system.go
We try to collect system data (e.g. CPU, memory usage, etc., shown in "System" page) when it's a self hosted database server and the database server is in the same instance as the collector's.
However, sometimes people would set the db host different from localhost or 127.0.0.1 even though the database is running locally. In that case, setting `always_collect_system_data` will help the situation, but it's not so obvious.
https://pganalyze.com/docs/collector/settings#self-managed-servers
In this PR, add a log during the test run if we detect 1) the server is self hosted 2) but it's detected as a remote host.
> Add logs for test run when system state collection is skipped

- input/postgres/relation_stats.go
- input/postgres/relations.go
Currently, if tables are locked in AccessExclusiveMode, we skip
collecting most table structure information and table and column
stats. We do this since the lock would conflict with the lock the
collector needs and potentially cause cascading locking problems and
impact the application. However, we're not checking the locktype, so
the collector also avoids collecting stats for tables with
AccessExclusiveMode locktype = 'tuple' locks, which do not actually
block collection. These can be fairly common, e.g., if a transaction
issues a `SELECT FOR UPDATE` query while another transaction has
already obtained a `SELECT FOR UPDATE` lock.
Relax the locking requirements by ignoring AccessExclusiveMode
locktype = 'tuple' locks when collecting schema structure and stats.
> Relax locking requirements for collecting table stats

- input/system/selfhosted/logs.go
Whilst we currently explicitly call out to "docker" for this experimental way of reading local logs during development, we technically also support podman when its available with the "docker" alias. However, podman requires arguments to be set before the container name. Fix support for this type of setup. This keeps compatibility with docker, which accepts arguments in either order.
> Docker log tail: Re-order args to also support podman aliased as docker

- config/config.go
- config/read.go
- helper/main.go
- input/postgres/data_directory.go
- input/system/selfhosted/system.go
- main.go
Currently, for gathering system stats on self-hosted systems, we look
up the current working directory of the postmaster process. This
usually works, but if customers have an unusual configuration, it can
find the wrong directory.
Instead, use the current method only as a fallback, and look at the
data_directory setting instead. This is readable with
pg_read_all_settings (part of pg_monitor), so it should be accessible
to us in most configurations.
> Improve data directory detection

- config/config.go
- config/read.go
- logs/querysample/tracing.go
- main.go
- runner/logs.go
> OpenTelemetry Integration: Refactoring, support configuring OTLP headers

- main.go
- output/compact_activity.go
For historic reasons, we were only normalizing pg_stat_activity query texts when `filter_query_sample` was set to `all`, not `normalize`, which has a similar intent.
Whilst we could also control the filtering of pg_stat_activity query texts with the `filter_query_text` setting (which today controls whether pg_stat_statements query texts are re-normalized, and is enabled by default), this is intentionally
not done here. The main motivation to not do this for now are performance implications of running normalize every 10 seconds for many active queries, and we may adjust this in a future commit based on more benchmarks.
> Activity snapshots: Normalize queries for "filter_query_sample = normalize"

- input/postgres/statements.go
- output/transform/postgres_statements.go
- state/postgres_statement.go
This could have caused statistics to be incorrect in Postgres 14+ when the same query was called both from within a function (toplevel=false) and directly (toplevel=true), with pg_stat_statements track set to "all".
If affected, the issue may have shown by bogus statistics being recorded, for example very high call counts, since the statement stats diff would not have used the correct reference.
Fix by including toplevel attribute for internal tracking, matching the [pgssHashKey struct](https://github.com/postgres/postgres/blob/master/contrib/pg_stat_statements/pg_stat_statements.c#L148) in pg_stat_statements.c where this data originates.
> Postgres 14+: Include toplevel attribute in statement statistics key

- logs/querysample/tags.go
- logs/querysample/tags_test.go
See the spec, especially for the parsing in https://google.github.io/sqlcommenter/spec/#parsing
This PR will support query tags with SQLCommenter format, like `key='value'` (value is surrounded by single quotes). I think it's quite essential to support this as I believe Active Record Query Logs uses SQLCommenter format by default.
I confirmed that the current code doesn't support picking up `traceparent` when the format is SQLCommenter, and this should fix it.
https://api.rubyonrails.org/classes/ActiveRecord/QueryLogs.html
> Support query tags with SQLCommenter format

- CHANGELOG.md
- contrib/helm/pganalyze-collector/Chart.yaml
- packages/Makefile
- util/version.go
Maybe we should include https://github.com/pganalyze/collector/pull/468 as it's a high severity?
> Release 0.52.2

- .github/workflows/ci.yml
- output/compact.go
- state/state.go
The high frequency of compact snapshots causes them to create the vast majority of log lines in the default (info) log level. That makes it difficult to find logs related to errors when debugging an issue.
This PR summarizes the 6+ compact snapshots sent per minute into a single log line:
```
Compact snapshots submitted: 6 activity, 2 logs
> Summarize compact snapshot logs to reduce noise

- input/postgres/statements.go
Starting from Postgres 14, there is a concept called `toplevel` but if you're using the older version of pg_stat_statements extension, this `toplevel` not appearing during the stats collection, therefore it can still cause the bug that was fixed in https://github.com/pganalyze/collector/pull/463
With this PR, we detect such case during the test run and warn folks to upgrade pgss.
> Add a special error message during test run when Postgres 14+ is using the older pgss

- logs/querysample/tracing.go
- logs/querysample/tracing_test.go
- util/tracing.go
- util/tracing_test.go
Currently, we generate an OpenTelemetry tracing span using `sample.OccurredAt` and `sample.RuntimeMs` derived from logs. This approach generally functions well, however, it can encounter precision issues due to the log timestamp format.
Specifically, timestamps with lower precision (e.g., hundredths of a second like `12:34:56.78`, seen with RDS) result in spans ending at the 100th millisecond mark. This leads to misalignment, causing the span to appear earlier or later than it should.
To solve this, we would like to introduce a new tracestate for pganalyze. With tracestate, we can provide a vendor-specific trace identification information. We will use the key `pganalyze` for this, while the value is a list, containing a member with semicolon (`;`) separated format. Each member should also …
> Support pganalyze tracestate to set start time of the span

- output/compact.go
Due to the way the code was written, we would either count the current snapshot, or emit statistics - but even if we emit statistics we still need to increment the snapshot count.
> Compact snapshot stats: Fix incorrect counting for current snapshot

- input/full.go
- input/postgres/statements.go
- scheduler/scheduler.go
Some situations can cause pg_stat_statements data collection to fail, e.g. a timeout when the query text file got too large. Previously we treated the whole snapshot as having failed in such situations, only reporting an error snapshot to pganalyze, without any statistics.
This caused two issues:
(1) Unrelated data, such as schema statistics, got lost in the face of
temporary pg_stat_statements issues
(2) The early return from the collection logic caused us to skip over
the optional pg_stat_statements_reset() facility in the collector,
which otherwise would have allowed the collector to recover from
an overly large file (by resetting it, allowing the next collection
to succeed)
Fix by treating pg_stat_statements errors as a collector error in the snapshot, but continuing afterwards …
> Allow pg_stat_statements failures and continue snapshot processing

- output/compact.go
- output/full.go
This adjusts the recently changed compact snapshot information to be closer to what it was before, and adds "full" to the full snapshot message for clarity:
```
I [default] Submitted compact snapshots successfully: 5 activity, 2 logs
I [default] Submitted full snapshot successfully
```
Note that the compact snapshot message continues to emitted once per minute, not continuously as in past releases.
> Snapshot submission: Streamling wording for success message

- logs/querysample/tags.go
- logs/querysample/tags_test.go
While I was testing, I realized that tracestate is not propagating well when it's passed with marginalia shape.
This PR should fix it.
Honestly, I'm not 100% sure if "With sqlcommenter format (key='value'), key shouldn't include ":"" is accurate, but I think it's a safe assumption to make.
With sqlcommenter, the tracestate might be URL escaped, but let's assume that it's not for marginalia here.
> Support tracestate query tag with marginalia shape

- input/system/azure/logs.go
The current logic looks like falling back to the `NewManagedIdentityCredential` when `NewWorkloadIdentityCredential` isn't created, but actually it's not working like that way. Instead, it's erroring out when `NewWorkloadIdentityCredential` failed to be created, making it impossible for the VM deployed collector to try out managed identity credential (workload identity credential is used for AKS setup).
With this change, avoid raising an error and early return when `NewWorkloadIdentityCredential` returns an error. Instead, try `NewManagedIdentityCredential` then raise an error when both of them failed.
For the reference, if `AZURE_AD_CLIENT_ID` is not specified and multiple identities are assigned to the VM, you'd see the following error:
```
E [default] ERROR - Could not get logs through …
```
> Fall back to managed identity with workload identity credential error

- input/postgres/relation_column_stats.go
- input/postgres/relation_stats.go
Decoupled the refactor bit from https://github.com/pganalyze/collector/pull/476
I think this refactor is good (also good use of `StatsHelperExists`), and maybe I didn't even need to decouple, but just wanted to do to make that PR a bit simpler.
> Refactor to have a dedicated file for relation_column_stats

- config/config.go
- config/read.go
- input/system/selfhosted/logs.go
- input/system/selfhosted/syslog_handler.go
Add TLS support for Log Insights integration using syslog. Tested with Aiven + rsyslog integration with a self-signed certificate, it went well.
With this PR, we will introduce 4 config params:
* LogSyslogServerCAFile: optional, but required if the cert is self-signed
* LogSyslogServerCertFile: cert
* LogSyslogServerKeyFile: key
* LogSyslogServerClientCAFile: optional, but required if the client is providing a cert and it is self-signed
Preparing the cert part is a bit hand wavy here, but I think we can improve a document around here.
Docs PR: https://github.com/pganalyze/pganalyze-docs/pull/210
> Support TLS for syslog

- input/postgres/relation_stats.go
- input/postgres/relation_stats_aux.go
- input/postgres/relation_stats_citus.go
Some refactor that I would like to split from https://github.com/pganalyze/collector/pull/476
Currently, in order to support collecting relation stats information for Citus, the name "ext" is used, like `handleRelationStatsExt`. In https://github.com/pganalyze/collector/pull/476, I would like to use the term `RelationStatsExtended` for the extended statistic info.
To avoid these two mixing together, I would like to rename the Citus one specific to Citus.
> Rename rel stats collection func for Citus not to use ext

- integration_test/Makefile
We don't expect any warnings and should confirm that's the
case. Warnings will often also cause a test failure, but that can be
hard to track down since the collector log is a number of lines
earlier than the diff failure output, and there's a lot of output in
integration tests.
> Warn in guided setup integration test when collector warnings present

- .github/workflows/release.yml
- integration_test/Makefile
Currently, we have an undocumented release step 7, to build arm build and upload to the release:
https://github.com/pganalyze/collector/blob/25220c7e66c7e60aed5122aaae706245c23bc467/CONTRIBUTING.md#release
With this PR, we use Ubicloud to build the collector on the arm runner and upload it, within the release GitHub Action.
* Updated `setup-protoc` version to use `149f6c87b92550901b26acd1632e11c3662e381f`, which support setting up protoc with arm
* Skip Citus integration test with arm, since the Citus base docker image doesn't have arm64 arch version (https://hub.docker.com/r/citusdata/citus/tags)
> Build and release arm build using ubicloud

- integration_test/Makefile
In passing, use "uname -m" instead of "uname -p", since "-m" is the more standard flag to use.
> Integration test: Adjust citus check to correctly exclude aarch64

- CHANGELOG.md
"external" => "extended" (I got that wrong in my suggestion on the release PR)
> CHANGELOG: Fix typo in release notes

- input/postgres/schema.go
The view `pg_stats_ext` was introduced from Postgres 12, so let's only try to collect extended stats data if the version is 12 and above.
https://www.postgresql.org/docs/current/view-pg-stats-ext.html
> Only collect extended stats for postgres version 12 and above

- packages/src/Dockerfile.build.deb-systemd
- packages/src/Dockerfile.build.rpm-systemd
This is an interim fix until we can upgrade the Ruby version used for fpm in the build scripts. That is slightly complicated due to the base OS being intentionally old (to keep an older glibc base version).
> Package build: Pin dotenv version to last one that supports Ruby 2.7

- input/system/selfhosted/syslog_handler.go
When configuring rsyslogd for RFC5424 output with the RSYSLOG_SyslogProtocol23Format template, it adds a leading space that we didn't anticipate correctly.
> Syslog handler: Allow leading spaces before parts regexp

- contrib/helm/pganalyze-collector/Chart.yaml
Just realized that I forgot to fix one typo (I forgot to update there to 0.54.0)
> Fix typo with version in helm chart

- config/read.go
Currently, the env var corresponding to the config setting
api_base_url is PGA_API_BASEURL, which has different spacing.
Allow both (but prefer the documented version).
> Accept PGA_API_BASE_URL env var in addition to PGA_API_BASEURL

- README.md
Our get_relation_stats_ext helper is specified as returning a row that
starts with two text fields, but these come from the pg_stats_ext view
and are actually `name` columns (the type for Postgres identifiers).
Postgres 13 introduced an implicit name-to-text cast, so in that version
and newer versions, our helper function works fine, but on Postgres 12
it fails with
ERROR:  return type mismatch in function declared to return record
DETAIL:  Final statement returns name instead of text at column 1.
CONTEXT:  SQL function "get_relation_stats_ext"
Update the function definition to use explicit casts for the first two
columns.
> Fix extended statistics monitoring helpers for Postgres 12

- input/postgres/relation_stats.go
Due to the way how pg_stat_all_tables and pg_statio_all_tables are defined, its significantly more expensive to query through the views when a table filter is in place, since all the data gets pulled, only for the filter to be applied afterwards.
Instead, call the underlying pg_stat_get* functions directly, which has the same effect as querying the views (as they are simple views without any security barrier), and shows a major speedup in cases where a large portion of tables is filtered out. This also should provide a minor speedup in regular operations, even with no table filter in place.
> Relation stats: Call pg_stat_get_* directly instead of using system views

- input/system/tembo/logs.go
At Tembo, we recently started to collect and serve logs from `AppServices` in a Tembo Instance's namespace alongside Postgres logs. This means that the collector will receive those logs by default, which is not what we want.
This PR resolves the issue by filtering the logs we receive by the Postgres pod name.
> Tembo Logs: Filter Out App Service Logs

- config/read.go
- main.go
- state/state_file.go
- util/heroku.go
- don't complain about a missing state file: this is expected since
dynos are stateless and there's unlikely to have been a previous
run of the collector in the same dyno
- do nothing on reload: our reload mechanism looks for a running
collector process, but on heroku, that's going to be in a different
dyno
> Fix spurious errors on Heroku

- main.go
- runner/emit_test_lines.go
Currently, we only surface errors, and produce no output on success
(or if EXPLAIN-related settings are disabled).
Update the check to emit output on success and guidance when the
settings are disabled.
> Add more verbose output for the --test-explain flag

- input/postgres/statements.go
- state/postgres_version.go
Whilst 17 is still in development, this change landed a while ago, so its likely to stay in, and I think we're okay to take this for now (since otherwise statement stats don't work on 17 at all).
> Update pg_stat_statements logic to match field names in Postgres 17

- logs/analyze.go
- logs/analyze_test.go
We missed handling this for Postgres 16, which causes autovacuum log lines to not be parsed correctly. This adds three new data points to the details array: frozen_pages, frozen_page_percent and tuples_frozen.
Upstream commit that added this: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=d977ffd923d;hp=b76fb6c2a99eb7d49f96e56599fef1ffc1c134c9 - this is in PG16, as seen on GitHub page for that commit: https://github.com/postgres/postgres/commit/d977ffd923d
> autovacuum log parsing: Correctly parse "frozen: " line in Postgres 16+

- .github/workflows/release.yml
- CONTRIBUTING.md
- README.md
- contrib/helm/pganalyze-collector/values.yaml
Closes https://github.com/pganalyze/collector/issues/328
🗒️ I changed the direction quite a bit, so updating the PR summary here too.
With this PR, I added the following steps in the release CI:
* build_charts (new!): this creates a helm package of pganalyze-collector (e.g. pganalyze-collector-0.55.0.tgz)
* release (existing): added the section to upload created pganalyze-collector-0.55.0.tgz to the GitHub release
* release_charts (new!): this uploads a helm package, as well as update index.yaml file and update it to s3
In theory, CI will do the helm chart release for us so we don't need to do anything further.
I also did the following to set up charts.pganalyze.com:
* created s3 bucket and did the CNAME thingy, etc. to make sure the host works
* uploaded index.yaml, …
> Add helm chart package support

- config/config.go
- input/postgres/establish_connection.go
- util/awsutil/rds.go
Previously IAM authentication would fail with "PAM authentication failed" when the port was not explicitly set in the collector configuration.
This instead falls back to the default (5432), which is the typical port used on Amazon RDS and Aurora.
In passing use the same logic in the fallback logic for identifying RDS instances by their hostname, since the DB instance list also always includes the port, and this was likely broken as well if the port wasn't set explicitly.
> Amazon RDS/Aurora IAM Authentication: Default to DB port 5432

- CHANGELOG.md
- input/postgres/buffercache.go
- input/postgres/explain.go
- input/postgres/relation_bloat.go
- input/postgres/relation_column_stats.go
- input/postgres/relation_stats_ext.go
- input/postgres/replication.go
- input/postgres/statements.go
- integration_test/Makefile
- integration_test/guided-setup.snapshot-subset.json.expected
- setup/steps/ensure_pganalyze_schema.go
- setup/util/helper_functions.go
Some of the README documentation was out of date, and it's hard to
keep these two copies in sync, so for a more seamless onboarding
experience, we'll focus our documentation on https://github.com/pganalyze/pganalyze-docs/
In passing, drop the get_stat_replication helper, which is no longer
necessary with pg_monitor.
> Update links that point to README to point to official docs instead

- contrib/docker-entrypoint.sh
- main.go
With this change, `docker run` will take more args than just `test`, `test-explain`, or `collector`. This allows users to run things like `docker run --env-file pganalyze_collector.env quay.io/pganalyze/collector:stable test -v` to run the test with verbose mode.
----
(previous comment)
Please correct me if I'm doing something useless, though I always find it difficult to run with the debug log mode with a Docker setup. Maybe I can run `docker run .... quay.io/pganalyze/collector:stable /home/pganalyze/collector --statefile=/state/pganalyze-collector.state --no-log-timestamps --verbose`?
Not sure, but I thought it won't hurt to add some new command, so that we can do `docker run .... quay.io/pganalyze/collector:stable /home/pganalyze/collector collector-verbose` to launch the collector …
> Allow collector to run in verbose log mode with Docker

- Dockerfile
- contrib/docker-entrypoint.sh
- contrib/helm/pganalyze-collector/values.yaml
Currently, `/home/pganalyze/.pganalyze_collector.conf` is used to store the config file when `CONFIG_CONTENTS` env var is passed, with Docker. However, this was failing to work when using helm chart, because `/home/pganalyze` is readonly.
With this PR, update that location to `/config/pganalyze-collector.conf`, then create such dir in Docker side. Also make sure to add this dir in helm chart side too, so that it'll be properly written within the docker entrypoint.
> Update a config file location with Docker

- input/full.go
- input/postgres/schema.go
- main.go
- runner/generate_helper_sql.go
- state/state.go
Passing the new "--generate-stats-helper-sql" command to the collector will generate a SQL script that can be passed to "psql" to install stats helpers (e.g. for collecting column stats) on all configured databases for the specified server.
The command takes the name of the configuration section of a specific server in the collector configuration (e.g. "server1").
It can be used manually by saving the output to a file, or by piping it to psql like this:
```
pganalyze-collector --generate-stats-helper-sql=server1 | psql -f -
```
Make sure to execute the generated SQL as an administrative user or database owner (not the pganalyze user!) in order for the SECURITY DEFINER functions to have sufficient privileges assigned.
> Add --generate-stats-helper-sql command to generate helpers psql install script

- README.md
Use it to point to our official docs. Users may still be pointed here from, e.g., log output of old collector versions, so we can make it easier to find the right documentation.
> Restore "Setting up a Restricted Monitoring User" section

- runner/generate_helper_sql.go
Column stats collection on RDS with Postgres 16 is currently failing with:
```
error collecting column statistics: pq: permission denied for attribute pg_subscription.subconninfo
```
This PR fixes that by excluding internal Postgres tables in `get_column_stats` and `get_relation_stats_ext` helper functions, since we'd later discard the data anyway.
Companion PR: https://github.com/pganalyze/pganalyze-docs/pull/249
> Exclude internal Postgres tables from stats helper functions

- .github/workflows/release.yml
Current release is failing with the following error:
> It looks like you might be trying to authenticate with OIDC. Did you mean to set the `id-token` permission? If you are not trying to authenticate with OIDC and the action is working successfully, you can ignore this message.
https://github.com/pganalyze/collector/actions/runs/8756953063/job/24037550811
Looks like I indeed missed that: https://github.com/aws-actions/configure-aws-credentials?tab=readme-ov-file#oidc
For the [v0.56.0](https://github.com/pganalyze/collector/releases/tag/v0.56.0) release, I'll manually update the chart file to s3 in the meantime.
> Add id-token: write permission for helm chart upload workflow

- logs/analyze_test.go
- logs/querysample/querysample.go
We saw some cases where the explain output text is including the part of query for the case with Heroku logs when the new line is added in the middle of query text because query text is too long.
This is purely a workaround and I'm not even sure if this is a good workaround (probably bad), but this at least will fix the issue, at least with the customer who is seeing the issue.
I think the change is pretty safe. If the explain output is not starting with the capital letter (the first word should be a node type), I think that's a problem anyways, so trying something different won't hurt.
I glanced https://github.com/postgres/postgres/blob/89ad3e1316bf0374f9e57456bf2888d14bf070f6/src/backend/commands/explain.c#L1360 to see what the possible explain output to justify. Technically I'm not …
> Handle newline within auto_explain query text with text format

- output/compact.go
- output/full.go
The message currently says "Error uploading to S3", but with direct
snapshot upload or Enterprise server with different object storage
configured, snapshots may be going somewhere else.
Remove "S3" from the message.
> Correct snapshot upload error message

- runner/generate_helper_sql.go
It looks like RDS has some custom patches that can run the permission
check for stats before running the related filter, causing a
permission failure fetching stats for tables that we don't want to see
in the first place (and that should be pruned by the `schemaname`
filter).
Ignore the 'pg_subscription' table explicitly.
> Work around RDS pg_stats and pg_stats_ext issue

- logs/analyze.go
- logs/analyze_test.go
Currently, setting `parsing_error` in [filter_log_secret](https://pganalyze.com/docs/collector/settings#pii-filtering-settings) only redacts the fragment in the main log line, while the following log line contains the statement in full:
```
ERROR: syntax error at or near "XXXX" at character 1 
STATEMENT: test;
```
With this PR, the statement is also redacted:
```
ERROR: syntax error at or near "XXXX" at character 1 
STATEMENT: XXXXXX
```
This is implemented by adding a duplicate `LogSecretMarker` so the statement can be redacted if either `parsing_error` or `statement_text` log filtering is enabled.
> Log filtering: redact statement for syntax errors

- util/awsutil/amazon.go
In a situation where both the web identity token file, role ARN, and assume role ARN are set, we now first retrieve credentials via web identity, and then assume the role specified as AWS_ASSUME_ROLE.
This helps with cross-account configurations on AWS in combination with the collector running in EKS.
* AWS only uses `AWS_ROLE_ARN`, not `AWS_ASSUME_ROLE`, so we're safe in that regard
> AWS: Allow setting both assume role and web identity/role ARN

- CHANGELOG.md
- packages/README.md
- packages/repo/Dockerfile.repo-rpm
- packages/src/Dockerfile.build.rpm-systemd
- packages/test/Makefile
Currently, build_packages CI is failing because of the EOL of CentOS 7 and the retirement of its mirror for packages.
https://serverfault.com/questions/1161816/mirrorlist-centos-org-no-longer-resolve
I've placed several workarounds, seems to be working locally. Until we have a better plan for how to retire CentOS 7 support, maybe we can use this workaround?
> Add workaround for CentOS 7

- input/system/google_cloudsql/logs.go
With AlloyDB, when the log line contains a new line, it was cutting anything after a new line unintentionally.
This updates the regex to make sure that all content will be kept.
Confirmed that it'll match: https://go.dev/play/p/ym6RhMU26ud
> Support multiline logs with AlloyDB

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/release.yml
- .github/workflows/test-packages.yml
- Dockerfile
I'm not addressing all the warnings for both Docker and GH Action, but we have too many now and I'm addressing some.
For GH Action version bump, I made sure that every bump is pretty safe. The `actions/upload-artifact` action had some breaking changes (which didn't affect to us), but otherwise all bumps are pretty much to support Node.js 16 deprecation.
https://github.com/pganalyze/collector/actions/runs/9770203430
> Address docker warnings and GH Action Node.js 16 deprecation

- config/config.go
- config/read.go
- input/postgres/relation_stats_aux.go
In some situations, the problems that DISABLE_CITUS_SCHEMA_STATS is
intended to solve are actually only with indexes, not with other
schema stats. By adding an index-specific setting, we can support more
functionality for affected users.
> Add option to avoid collecting distributed index stats for Citus

- main.go
Due to the way the signal handling is written, we stop checking the testRunSuccess channel once a SIGINT is received. However the code that marks the wait groups as done could only return once it finished writing to the channel, since it was unbuffered. Make the channel buffered so that the code can return as intended.
Fixes #561
> Test run: Avoid collector hanging when interrupted via CTRL+C (SIGINT)

- main.go
Its potentially confusing if we print the summary despite the run having been interrupted, since the summary will show "context canceled" errors that someone not familiar with Go terminology won't understand.
Instead, don't print anything, so its more clear the program was stopped in the middle of its work.
---
Note that we have an existing "Interrupt" message that is not affected by this:
```
lfittl@starfish pganalyze-collector % ./pganalyze-collector --test
2024/07/10 17:39:42 I Running collector test with pganalyze-collector 0.57.0
2024/07/10 17:39:42 I [server1] Testing statistics collection...
^C2024/07/10 17:39:43 E Interrupt
2024/07/10 17:39:43 E [server1] Could not process server: Get "http://localhost:5100/v2/snapshots/grant": context canceled
```
> Test run: Don't print summary if interrupted via CTRL+C (SIGINT)

- grant/default.go
- grant/logs.go
- input/full.go
- input/system/crunchy_bridge/client.go
- input/system/crunchy_bridge/system.go
- input/system/heroku/logs.go
- input/system/system.go
- input/system/tembo/system.go
- runner/activity.go
- runner/full.go
- runner/logs.go
This replaces all calls of "http.NewRequest" with
"http.NewRequestWithContext", to ensure that the HTTP client stops what its doing immediately when the context gets canceled.
The main motivation here is to better handle network connectivity problems to the pganalyze snapshot API, which otherwise make it seem like the collector hangs when trying to cancel a test run with CTRL+C (SIGINT).
> Allow HTTP clients to be cancelled by passing along context

- logs/analyze.go
For #566. A parse error can sometimes not include a statement line, so this PR updates the code to check for the statement's presence.
> Fix parse error handling when statement line is missing

- config/read.go
As seen in support ticket 5504, users may run into the duplicate server error when trying to set up the collector to monitor multiple databases in the same server. This PR updates the error message to note that `db_name` accepts a comma-separated list to monitor multiple databases.
> Improve duplicate server error message

- contrib/install.sh
- packages/repo/sync_deb.sh
As `apt-key add` is deprecated in Debian 11 (“Bullseye”) and Ubuntu 20.04 LTS (“Focal Fossa”), which are our minimal supported versions of the collector, let's remove the usage of it.
This thread has a great answer of why we shouldn't use `apt-key add`, and I updated the command to make sure to follow the best practice here.
https://askubuntu.com/questions/1286545/what-commands-exactly-should-replace-the-deprecated-apt-key
As a reference, the following message was shown during the installation process:
```
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
W: https://packages.pganalyze.com/ubuntu/noble/dists/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for …
```
> Avoid using apt-key command for Debian

- logs/parse.go
- output/compact.go
- output/full.go
- runner/logs.go
- state/logs.go
The server side already overwrites assigned log line/file IDs with ULIDs, so this does not make any practical difference for them, but may allow us to remove that logic on the server side in the future.
Collector provided snapshot IDs are currently mainly intended for debugging purposes (the server-side assigns its own ID), but it seems reasonable to use a more index-friendly ID here as well.
> Utilize UUID v7 for log lines/files, as well as snapshot IDs

- input/system/crunchy_bridge/client.go
This handles the case where the HTTP response status code is not `200 OK` or the response body is empty in `client.go`. Instead of returning a `nil` error, it now returns a formatted error message with the status code and response body. This improves error handling and provides more information about the issue.
I hit this issue when PGAnalyze collector stopped working for me and the snapshots failed to be proccesed due the error 
```
Could not process server: runtime error: invalid memory address or nil pointer dereference
```
Due to the `nil` error, the subsequent code (https://github.com/pganalyze/collector/blob/5e8eab6bb9a6cdf41e8874fdd1e8b95fd1ee18fc/input/system/crunchy_bridge/system.go#L35) panics due to `clusterInfo` being `nil`. It turned out my CrunchyBridge API Key had expired …
> fix: Handle unexpected status code in GetClusterInfo

- input/system/azure/logs.go
- input/system/azure/logs_test.go
- logs/parse.go
- state/state.go
This PR fixes two things of Azure log handling (Log Insights):
1. Handle the case Flexible Server returns `LogicalServerName` in record
* This bug was found in https://github.com/pganalyze/collector/pull/494#issuecomment-2297975788
* Previously, it was assumed that it won't be returned with Flexible Server
* Instead, use `resourceId`, which contains resource type, to identify if it's single server or not
2. Fix parse errors with Cosmos DB logs
* Lukas mentioned that this was reported by the customer that the current logic doesn't work with Cosmos DB
* Confirmed that it doesn't work due to how Cosmos DB doesn't add log level after the prefix
* Applied some workaround as a fix (similar to Flexible Server but a bit more complex)
> Improve Azure log handling to support Flexible Server and Cosmos DB better

- config/read.go
A customer ran into this because they specified some configuration settings in uppercase (`DB_NAME`). We currently silently skip incomplete sections, which is pretty confusing.
Separately, I considered parsing config keys in a case-insensitive manner, but since some but not all of our environment variable keys are identical to our config file keys, I thought this would be more confusing than a clear error. I'm open to revisiting that decision.
> Error out on incomplete config sections

- go.mod
- go.sum
- logs/analyze.go
- logs/analyze_test.go
- vendor/github.com/pganalyze/pg_query_go/v5/CHANGELOG.md
- vendor/github.com/pganalyze/pg_query_go/v5/Makefile
- vendor/github.com/pganalyze/pg_query_go/v5/README.md
- vendor/github.com/pganalyze/pg_query_go/v5/parser/include/pg_query.h
- vendor/github.com/pganalyze/pg_query_go/v5/parser/parser.go
- vendor/github.com/pganalyze/pg_query_go/v5/parser/pg_query_normalize.c
- vendor/github.com/pganalyze/pg_query_go/v5/parser/pg_query_scan.c
- vendor/github.com/pganalyze/pg_query_go/v5/pg_query.go
- vendor/modules.txt
Utility statements can include database secrets, so this PR classifies utility statements under `filter_log_secret = credential` (which is enabled by default as of #556), so they're redacted from the logs.
Depends on https://github.com/pganalyze/pg_query_go/pull/116
> Redact utility statements by default

- main.go
> Fix hang for --discover-log-location flag

- CHANGELOG.md
- contrib/helm/pganalyze-collector/Chart.yaml
- packages/Makefile
- util/version.go
Other pending PRs:
- #589
- #588 ?
- ~one coming up as a minor follow-up to #494~ (this was actually done in #494; I missed it when looking at the code)
> Release 0.58.0

- config/config.go
- runner/logs.go
- Avoid log_line_prefix check in log test in new mode
- Drop obsolete TODO
> Drop supported log_line_prefix check in test

- README.md
- app.json
Just noticed that it's using the old logo. Let's update to the new one.
Old
New
Also adding www to heroku.com as it first redirects www.heroku.com and we can skip that redirect by nicely adding www.
> Update logo for Deploy to Heroku button

- logs/analyze.go
- logs/analyze_test.go
- logs/querysample/querysample.go
- runner/logs.go
- state/postgres_query_sample.go
Starting from Postgres 16, auto_explain outputs the query parameters (bind parameters), used for prepared statements.
With this PR, the collector supports to extract these parameters and send them within query samples, with both JSON and TEXT format.
This PR also improves new lines support with text format. Previously, the text format is not parsing a query text and an EXPLAIN output well, and if the query text contains new lines, it was simply failing to extract them correctly.
With this PR, first we try to match the text format auto_explain with a newly introduced "Query Parameters:", which makes our life easier to actually separate a query text and an EXPLAIN output.
If that doesn't go well, we try to match with the cost output: …
> Support Query Parameters with auto_explain and support new lines better with text format

- main.go
In #494, I missed updating the --analyze-logfile flag. The flag is
intended to analyze a logfile "offline", which does not work with the
new mechanism, since that relies on being able to read the server's
log_timezone and log_line_prefix.
This adds additional flags to pass that information to the
--analyze-logfile path. The timezone defaults to UTC; the prefix is
required.
> Fix --analyze-logfile flag

- input/postgres/functions.go
- input/postgres/relation_stats.go
- input/postgres/relations.go
- input/postgres/schema.go
- input/postgres/types.go
- input/postgres/version.go
- state/postgres_version.go
Previously the collector would emit system catalogs that are only existing on EPAS ("sys" schema and child schemas), causing unnecessary schema information to show in the pganalyze dashboard.
Here we fix this by introducing EPAS-specific filtering of system catalogs, and share the system catalog filter logic across all files that use it.
Further, EPAS allows function signatures to be re-used between functions and procedures (presumably this was allowed before upstream Postgres added CREATE PROCEDURE), like this:
```
BEGIN;
CREATE FUNCTION test() RETURNS void AS $$
BEGIN
RAISE NOTICE 'test function';
END;
$$ LANGUAGE plpgsql;
CREATE PROCEDURE test() AS $$
BEGIN
RAISE NOTICE 'test procedure';
END;
$$ LANGUAGE plpgsql;
COMMIT;
SELECT prokind, pronamespace, …
```
> Improve support for EDB Postgres Advanced Server (EPAS)

- runner/websocket.go
Followup to #583, this ensures that a test run shows an error if the websocket entirely fails to connect.
> Improve test run error reporting for WebSocket

- input/postgres/statements.go
Currently when processing `pg_stat_statements` data we collect all query texts into memory, then discard them in favor of pg_query's normalized version. This PR reduces memory pressure by immediately normalizing each query text instead of collecting them into a map.
Using the below benchmark, this PR reduces memory usage from 16 MB to 14 MB.
```sh
go test -bench=. -benchmem
BenchmarkPgStatStatements-10               7     143591024 ns/op    16130617 B/op     178235 allocs/op
BenchmarkPgStatStatements-10               8     145522057 ns/op    14261621 B/op     177960 allocs/op
```
<details><summary>Benchmark:</summary>
```go
package main
import (
"testing"
"context"
"log"
"os"
"github.com/pganalyze/collector/input/postgres"
"github.com/pganalyze/collector/state" …
```
> Reduce memory usage when processing pg_stat_statements

- logs/parse.go
- logs/parse_test.go
Raised as part of open case (5773) with support regarding a memory leak. Will link PR in ticket. 
It is possible for the username and the database to be empty for some log messages. For example with CloudSQL the vacuum analysis logs are output as
> 2024-10-04 06:38:28.316 UTC [2569017]: [1-1] db=,user= LOG:  automatic vacuum of table \\\"database_name.pg_catalog.pg_database\\\": etc
This previously caused a bug where these lines were being treated as incomplete, resulting in a memory leak as "the rest" of the line was awaited (to stitch together logs that appear over multiple lines).
The ultimate result of this is that vacuum logs on CloudSQL never make it to PgAnalyze and therefore are not available in log insights or used as part of the vacuum advisor.
This commit fixes this by changing …
> Handle the database / user being empty

- input/system/google_cloudsql/logs.go
- logs/querysample/querysample.go
- util/clean_http_error.go
For support ticket 5773, I noticed that some places in the code we compile regular expressions at runtime for regular expressions that don't change. This PR fixes that, which should reduce CPU/memory usage.
> Build more regular expressions at boot time

- input/postgres/relation_column_stats.go
- input/postgres/superuser.go
- runner/generate_helper_sql.go
As documented on https://github.com/pganalyze/pganalyze-docs/pull/285, Postgres 17 added new columns to `pg_stats` which broke the `pganalyze.get_column_stats` helper function. This PR updates the function to `RETURNS TABLE` so any future additions won't break the function again.
But since that's a backwards-incompatable change requiring `DROP FUNCTION` instead of `CREATE OR REPLACE FUNCTION` this PR also adds an additional runtime check to explain the necessary steps to users.
> Update get_column_stats for Postgres 17

- packages/repo/Makefile
RPM base packages have changed and no longer contain an init system by default. Since we mainly care about having a process running to then issue exec commands under, we can use a sleep here instead to avoid failure.
> Packages repo sync: Use sleep instead of /sbin/init

- input/postgres/statements.go
It would be ideal to show this warning in the UI, but we can start from showing it with test run.
With Postgres 14+, `toplevel` (provided by pg_stat_statements 1.9+) is going to be really important to collect proper stats. Otherwise, we will collect stats without `toplevel`, which can cause the same query to have two version (with or without toplevel), which can lead to the incorrect metrics like "queries per min".
For instance, query A has stats with toplevel true and false, and true one has 100,000 calls and false one has 10 calls. Let's say the collector run will pick up the 10 calls for the query A and the following collector run will pick up 100,000 calls for it, which will result the diff to be almost 100k, making the "queries per min" to be 100k even though it's not true. It is …
> Add error when pgss version is below 1.9 with Postgres 14+

- logs/stream/stream_test.go
Followup to #607, this should fix the inconsistent test failure we're seeing by moving the output string generation after its array is sorted by the test.
```
--- FAIL: TestAnalyzeStreamInGroups (0.01s)
stream_test.go:390: For zero
first
second
third
: log state diff: (-want +got)
-"zero\nfirst\nsecond\nthird\n"
+"third\nzero\nfirst\nsecond\n"
FAIL
```
> Fix inconsistent test failure

- input/postgres/relation_column_stats.go
- input/postgres/schema.go
Followup to #610, this makes it so we only fall back to querying `pg_stats` directly on Postgres 17 and older, since the old function definition will still work until the database server is upgraded.
> Collect column stats using helper on Postgres < 17 despite warning

- input/postgres/statements.go
#605 succeeded in reducing memory usage, but it also caused collector query time in pg_stat_statements to increase. This PR tries to solve both issues by writing query texts to a tempfile so the query can finish quickly, and then reading each query text in one-by-one to keep memory usage down.
> Store query texts in temp file

- logs/parse.go
Our existing log parsing regular expressions may lead to ambiguity in
parsing log line prefixes for some log lines.
Ensure we only look for identifiers (role name, application_name, and
database name) up to the default identifier length limit (63 bytes) to
reduce ambiguities.
> Log Insights: Use more specific log parsing regexp

- contrib/systemd/pganalyze-collector.service
See docs in https://www.freedesktop.org/software/systemd/man/latest/systemd.resource-control.html#MemoryMax=bytes (and the note about MemoryLimit at the end).
Given usage patterns for the collector MemoryMax makes more sense than MemoryHigh here.
MemoryMax was added in systemd 231 in 2016: it should be available on all our supported platforms.
> Update MemoryLimit to MemoryMax in systemd config

- config/config.go
- config/read.go
Adds DB_URL_FILE and DB_PASSWORD_FILE
This lets users specify these credentials via the filesystem to better
support NixOS flakes and systemd credentials.
Based on #595
> Add DB_URL_FILE and DB_PASSWORD_FILE

- logs/replace.go
- logs/replace_test.go
In a25800b1a1e32c62dcc74587a2dbf7503e977211, we changed the way
redaction works for PII filtering. The change did not account for
detail log lines, leading to all log lines always being redacted.
Update the redaction mechanism to check for a parent log line.
> Fix over-eager PII filtering

- input/postgres/buffer_cache.go
Followup to #633. As mentioned in the [documentation](https://www.postgresql.org/docs/current/pgbuffercache.html):
>There is one row for each buffer in the shared cache. Unused buffers are shown with all fields null except bufferid. Shared system catalogs are shown as belonging to database zero.
The null values cause a type conversion error:
```
Scan error on column index 0, name "reldatabase": converting NULL to uint64 is unsupported
```
We might want to track them in the future, but for now this PR excludes them to work around the issue.
> Exclude unused pages from buffer cache monitoring

- runner/websocket.go
If the WebSocket encounters an error when writing data to the connection, the previous implementation called `cancelConn` but that wouldn't actually shut down the connection because it then `return`ed, shutting down the goroutine that would be listening for that cancel event.
In that case `server.WebSocket.Swap(nil)` would never be called, so the collector would continue trying to submit snapshots to the dead websocket connection.
This PR resolves that by moving the cleanup code to a separate function so it can be called directly when a write error occurs.
> Shut down WebSocket after write error

- packages/src/rpm-systemd/post.sh
The latter seems to no longer be available on Amazon Linux 2023. Since
addgroup is just a convenience wrapper around groupadd and we are only
using its basic functionality, we can switch to using groupadd
directly.
> Use groupadd instead of addgroup

- output/transform/transform_test.go
Since snapshots include query references and query plan references,
and since those can be orderered nondeterministically, the test can
fail if the snapshot is built with fields in an unexpected order.
The existing test tries to account for that by enumerating all
possible combinations, but this is very difficult to maintain, and
very difficult to scale to additional fields with this pattern.
Instead, rewrite snapshots to a canonical format to ensure comparisons
are stable. We can't just sort the array fields before serializing the
snapshot for comparison, since QueryReferences and similar items are
referenced by an index into their array. To work around that, we sort
the QueryReferences (tracking their original index), and rewrite all
entries that reference them to reference their new …
> Fix flaky transform_test.go

- runner/query_run.go
- state/state.go
This PR updates the query runner to submit the first error it sees, to avoid reporting an unhelpful `current transaction is aborted` error back to the server. `BEGIN READ ONLY` was a late addition to #628, so this wasn't caught in manual testing.
This also fixes an error I saw while testing this, where `server.QueryRuns` is nil:
```
panic: assignment to entry in nil map
goroutine 99 [running]:
runner.connect.func3()
runner/websocket.go:150 +0x4ac
created by runner.connect in goroutine 64
runner/websocket.go:113 +0xa44
> Improve query runner error handling

- input/system/azure/system.go
Spotted by Maciek in https://github.com/pganalyze/collector/pull/591/files#r1866387023
This function was previously returning the last value instead of the first value. This fix changes it and returns the value as soon as reading it.
Tested with the staging Azure database and it didn't break things.
> Azure Metrics: fix getFirstMetricValue to return the first value

- input/postgres/relation_stats.go
- output/transform/merge_partition_sizes.go
#635 improved the fidelity of statistics tracked for parent partitions, but in moving the code from SQL to Go it stopped reporting the size of parent partitions when `ignore_schema_regexp` is set to ignore the child partitions. This PR fixes #654 by bringing back the original SQL, but only applying it to child partitions that match `ignore_schema_regexp`.
> Track parent partition size when child partitions are untracked

- runner/websocket.go
The server repeatedly sends query runs that haven't started yet, but that can lead to a race condition where the server sends the query run again after it's already started but before it's completed. In that case, the websocket handler would erase the state that's already been stored (specifically `StartedAt`). This PR resolves that by only adding the query run if it's new.
> Handle repeated query run requests from server

- config/read.go
This adds the equivalent of the ini-style setting "max_buffer_cache_monitoring_gb" for the environment-based settings, which was missed when the setting was first added.
> Add MAX_BUFFER_CACHE_MONITORING_GB configuration variable

- contrib/install.sh
Additionally TODO to consider:
> Install script: Add AlmaLinux support

- go.mod
- go.sum
- vendor/golang.org/x/net/LICENSE
- vendor/golang.org/x/net/http2/client_conn_pool.go
- vendor/golang.org/x/net/http2/config.go
- vendor/golang.org/x/net/http2/config_go124.go
- vendor/golang.org/x/net/http2/config_pre_go124.go
- vendor/golang.org/x/net/http2/frame.go
- vendor/golang.org/x/net/http2/http2.go
- vendor/golang.org/x/net/http2/server.go
- vendor/golang.org/x/net/http2/transport.go
- vendor/golang.org/x/net/http2/unencrypted.go
- vendor/golang.org/x/net/http2/write.go
- vendor/modules.txt
Fixes CVE-2024-45338, which is a DOS style vulnerability that's not a practical problem, but may be flagged by dependency scanners.
> Update golang.org/x/net to v0.33.0

- input/full.go
- input/postgres/buffer_cache.go
- input/postgres/explain.go
- input/postgres/helpers.go
- input/postgres/plans.go
- input/system/selfhosted/logs.go
- runner/activity.go
- runner/logs.go
> Fix DB connection leak in buffercache logic, other connection related cleanup

- Makefile
Due to security enhancements in newer macOS versions, unsigned Go binaries may hang when built and executed locally. To prevent this, add code signing to `make build`.
> Sign built Go binaries for macOS

- input/system/azure/logs.go
- input/system/google_cloudsql/logs.go
- input/system/selfhosted/logs.go
- logs/parse.go
- runner/run.go
Currently, the collector log processing code assumes that the log
parser has always been initialized by the time we receive log messages
to process.  This is generally true, but it can be false if the
collector failed to connect to the database (to fetch log_line_prefix
to initialize the parser). That can lead to confusing errors (that
are not relevant to the root cause of the connection problem).
Skip attempting to process log lines when the log parser is not yet
initialized.
> Avoid trying to parse log lines when parser is not initialized

- runner/run.go
- scheduler/scheduler.go
- scheduler/scheduler_test.go
This PR updates the scheduler code so that the individual schedules are named by their frequency instead of using a purpose-specific name like, so for example `activity` becomes `TenSecond`. This change is needed for new features; it wouldn't make sense to capture 1 minute system stats using a `query_stats` schedule.
Since there's no need for this to be a dynamic map of schedules, I've replaced it with a statically-typed `Scheduler` struct. Note: `GetScheduler` was moved to the top of the file since it's the entrypoint into the file.
> Rename cron scheduler

- helper/main.go
Resolve symlinks when finding the Postgres data directory
We currently do not resolve symlinks when looking up $PGDATA from the
environment or the `data_directory` GUC setting. This can misattribute
storage costs to the wrong partition.
Always follow symlinks in the helper that resolves the data directory.
> Resolve data directory symlinks

- config/read.go
Currently, we assume that a Heroku-deployed collector will always
monitor Heroku databases specified through Heroku env config
(`HEROKU_POSTGRES_..._URL` values). It's possible to work around this
with `CONFIG_CONTENTS`, but can be an awkward workflow.
Allow monitoring databases deployed elsewhere by checking for
pganalyze-specific env vars first.
> Allow monitoring non-Heroku databases on Heroku

- input/system/azure/logs_test.go
- input/system/heroku/logs.go
- logs/parse.go
- logs/parse_test.go
- logs/replace_test.go
- main.go
- state/state.go
This was a bug introduced in #494. The code here was intended to pass
syslog-format messages to the old parsing code, but the old parsing
code did not actually use this code path for syslog. All the
syslog-specific processing is actually in
input/system/selfhosted/syslog_handler.go, and then the messages are
handed off to the parser. They will be matched against log_line_prefix
like any other log line.
Before #494 this worked fine, because #145 introduced a couple of
log_line_prefix options that could be used with this format.
The RsyslogRegexp was actually introduced in
73712dd996be4485b49ef79df5e5533131020ac9 (before our workflow used
pull requests consistently), and appears to have been intended to tail
log files in an older syslog format (the obsolete RFC3164, versus the
RFC5424 we …
> Drop special-casing of syslog format

- .github/workflows/release.yml
- .github/workflows/test-packages.yml
- packages/Makefile
- packages/src/Makefile
- packages/test/Makefile
This splits the package building and testing logic into x86_64 and arm64 targets, and allows triggering either both, or just one of them.
It also changes the GitHub actions for package testing and release to no longer use QEMU emulation (which recently started failing with segfaults), and instead uses separate runners for each architecture.
In passing remove stale "DOCKER_BUILDKIT=1" settings from package release action, which should no longer be needed since GH actions updated their Docker version.
> Build ARM packages without QEMU emulation

- CHANGELOG.md
- contrib/helm/pganalyze-collector/Chart.yaml
- packages/Makefile
- util/version.go
Pending PRs:
- #676
- #674
- #673
- #671 (but also waiting on https://github.com/pganalyze/pganalyze-docs/pull/305 )
- #678
We also need to fix the [Test Packages](https://github.com/pganalyze/collector/actions/workflows/test-packages.yml) GitHub Action.
> Release 0.65.0

- .github/workflows/release.yml
During the release process we group together the created packages as an artifact, to then upload them individually to the GitHub release entry.
Previously this was able to use a single "packages" zip file for both x86_64 and arm64 packages, but we now need to split this since we split the actions.
> GH release action: Fix "packages" name conflict

- contrib/helm/pganalyze-collector/README.md
- contrib/helm/pganalyze-collector/templates/deployment.yaml
- contrib/helm/pganalyze-collector/values.yaml
Hello, Internally we use external secret sources,
This PR adds the Ability for the environment variables to reference k8s objects that are per-defined under the pganalyze target namespace by cluster operators.
This solves an issue where a secret that does not conform to either existing methods:
- `extraEnv`: simple `key: value` strings
- `configMap` or `secret`: injection by using `envFrom` restricts the data fields conform to target environment variable names
By allowing helm operator to specify raw elements of the `env` spec of a container, it allows for additional options that are not currently covered.
I do not know how you do versioning for same appVersion patching of the chart-side only changes,
I see that most chart releases correspond to app releases, I ran `helm-docs` which is …
> Added ability to use raw envrionment variables maps in deployment

- runner/logs.go
While I was checking some other place, I realized that this part of the code is no longer reachable.
That particular error message from `azure.SetupLogSubscriber` was retired in https://github.com/pganalyze/collector/pull/415
https://github.com/pganalyze/collector/pull/415/files#diff-6f5880431e90b30b7cc480560bbf2f8e4a80fcbe85c03ca3cacae1276cb3512eL67
Let's make sure to remove it, also given that it's been a while since that change happened, I'd say that it's safe to remove the docs too (will do that in the docs PR).
> Remove special error handling as func no longer returns that error

- input/collector.go
- input/full.go
- input/postgres/buffer_cache.go
- input/postgres/databases.go
- input/postgres/establish_connection.go
- input/postgres/helpers.go
- input/postgres/log_pg_read_file.go
- input/system/azure/logs.go
- input/system/google_cloudsql/logs.go
- input/system/heroku/http_handler.go
- input/system/heroku/logs.go
- input/system/selfhosted/logs.go
- input/system/system.go
- input/system/tembo/logs.go
- logs/querysample/normalize_test.go
- main.go
- output/grant.go
- runner/activity.go
- runner/emit_test_lines.go
- runner/full.go
- runner/full_1min.go
- runner/generate_helper_sql.go
- runner/logs.go
- runner/run.go
- runner/websocket.go
- state/state_file.go
See individual commits:
- Rename reloadRun to reload
- Stop using deprecated ioutil package
- Save four thousand characters
- Drop unnecessary fmt.Sprintf
- Drop unnecessary fmt.Errorf calls
- Drop obsolete debugging output
- Drop unused function
This likely conflicts with #679 and #680; those should land first.
> Miscellaneous refactors and cleanup

- CONTRIBUTING.md
I had to figure this out when testing https://github.com/pganalyze/collector/pull/673 . I was not able to automate the test, but I think we should at least document the manual steps.
> Document manual testing of receiving logs over syslog

- input/postgres/collection.go
- input/postgres/collection_test.go
- runner/generate_helper_sql.go
- util/helpers/explain_analyze.sql
- util/helpers/get_column_stats.sql
- util/helpers/get_relation_stats_ext.sql
- util/helpers/get_stat_statements.sql
- util/sql_helpers.go
This accidentally broke in a recent refactoring, and caused helpers with no arguments (e.g. "get_column_stats") to not be detected correctly.
In passing refactor definitions of "get_column_stats" and "get_relation_stats_ext" helpers to be in SQL files.
> Helper function handling: Fix detection of functions without arguments

- input/postgres/replication.go
- input/postgres/statements.go
Previously, when the monitoring user is neither superuser nor has pg_monitor role, we were showing error messages saying that please use a superuser or create a helper function. While this is true for Aiven, especially for "creating a helper function" guidance, it's not true for other cases and when the user hits this with other providers, the error message is confusing and make it not clear which actions to take. Update the messaging to make it clear the next action for these cases.
This part, to link the Aiven doc was updated in https://github.com/pganalyze/collector/pull/532 and I did say "it's okay to use Aiven link", but we had some report from the other provider's customer who was confused by this error, so I think it's better to avoid showing the link. …
> Update messages when the monitoring user doesn't have a proper setup

- runner/activity.go
- runner/full.go
- selftest/summary.go
The collector pause warning may have made sense to us internally, but it doesn't help users identify the issue on their own. This PR rewords it to be very clear about how to resolve the issue, though it removes the "processing disabled" part to avoid making the message too long.
In passing, this PR also updates the test run summary to use simpler wording.
> Improve warning when collector is paused by duplicate process

- input/system/rds/system.go
We previously only checked for the Enhanced Monitoring Resource ARN to be set, but that field will remain set when Enhanced Monitoring was once turned on, but then turned off. Instead also check the monitoring interval which will be 0 in such situations.
Fixes missing system metrics on RDS when Enhanced Monitoring is turned off.
> Amazon RDS: Also check monitoring interval for Enhanced Monitoring

- util/helpers/explain_analyze.sql
With more tests, we noticed that passing parameter values and types separately to this function is not working well for several cases.
For values, as `pg_catelog.string_agg` will never emit NULLs and only aggregates non-null values, it fails when we actually want to pass NULL as a value. Use array_to_string instead as a workaround.
For types, when something like int4[] is passed, as it was quoting as "int4[]" previously, this also didn't work. We check the input type and if it matches to the regexp (type pattern, especially ones the pganalyze app would pass), it skips quote_ident.
> Better support for running EXPLAIN with pganalyze.explain_analyze helper

- input/postgres/server_stats.go
Aurora does not include the correct replication details in
pg_stat_replication, so check aurora_replica_status and use the older
of the two values to track XminHorizonStandby on the platform.
> Pick up the correct oldest xmin for Aurora replication

- input/system/crunchy_bridge/system.go
Currently, we're using gopsutil to fetch Crunchy's system metrics, assuming that the collector is deployed on Container Apps. Recently, with the change of cgroups with Container Apps, we are no longer able to pull these system info using gopsutil.
With this PR, instead of trying to get the system metrics using gopsutil, fetch these metrics from the API. Below is how it looks in the Crunchy Bridge UI and the pganalyze UI.
* pganalyze UI has "idle", which is kinda hack not to make other percentage inflate - you can see this more in the code comment
* In the pganalyze UI, we should likely be hiding load avg 5 mins and 15 mins as it doesn't exist and it's likely confusing to people for why it's zero
* "memory used" in Crunchy is shown as "Process Memory" in pganalyze
* In the pganalyze UI, …
> Fetch system metrics from API with Crunchy Bridge

- .github/workflows/release.yml
- .github/workflows/test-packages.yml
This effectively ends testing packages on Amazon Linux 2, since that requires CGroupsv1 which required Ubuntu 20.04. For now, leave the capability to test it in the relevant Makefile, in case we want to do manual testing.
> GH actions has stopped providing Ubuntu 20.04 runners, update to 22.04

- contrib/helm/pganalyze-collector/README.md
- contrib/helm/pganalyze-collector/templates/service.yaml
- contrib/helm/pganalyze-collector/values.yaml
Currently, when using a helm chart,  you can only expose one port for the [db_log_otel_server](https://pganalyze.com/docs/collector/settings#self-managed-servers).
With https://github.com/pganalyze/collector/pull/719, we should be able to create and expose more than one servers, and this helm chart update ensures that specifying to expose multiple ports of the collector is possible using a helm chart.
> Support specifying multiple ports for log OTEL servers

- input/system/azure/logs.go
- input/system/google_cloudsql/logs.go
- input/system/selfhosted/logs.go
- input/system/selfhosted/syslog_handler.go
- main.go
With https://github.com/pganalyze/collector/pull/719, we introduced a new flag `--very-verbose`, which enables emitting the incoming logs with Otel.
With this PR, expand the usage of `--very-verbose`, to enable the logging of incoming logs with Azure EventHub, Google Pub/Sub, and syslog.
See how the logs will look like in the following gist:
https://gist.github.com/keiko713/ebc0c8dbfcfd6ecb297fb1c1f3229e50
Internal memo: for https://github.com/pganalyze/pganalyze/issues/5073
> Use --very-verbose flag for logging received data from Azure EventHub, Google Pub/Sub, syslog

- contrib/install.sh
Tested manually with the Oracle Linux 9 instance and it worked. Given that Oracle Linux is 100% application binary compatible with RHEL, we should be okay adding it to the supported OS list.
> Add Oracle Linux as a supported OS to the install script
